#+TITLE: Ofertas de trabajo de interés para el MULCIA 

En esta página se recopilan las ofertas de trabajo de interés para los
estudiantes del [[http://master.cs.us.es/M%C3%A1ster_Universitario_en_L%C3%B3gica,_Computaci%C3%B3n_e_Inteligencia_Artificial][Máster Universitario en Lógica, Computación e Inteligencia
Artificial]] de la [[http://www.us.es][Universidad de Sevilla]].

Están en orden cronológico inverso por la fecha de su publicación en [[https://twitter.com/Jose_A_Alonso][Twitter]] o
el la [[https://listas.us.es/mailman/listinfo/master_mulcia][lista de correo del Máster]].

*** Julio de 2016

+ 27-Jul-16: Haskell developer job in India. http://bit.ly/2aJu5id #Job
  #Haskell 

+ 27-Jul-16: A Haskell developer for a full-time position at a Bay Area
  startup. http://bit.ly/2aJrLYs #Job #Haskell

+ 20-Jul-16: Two positions in computational linguistics (Postdoc or PhD
  student). Saarland Univ., Saarbruecken, Germany http://bit.ly/2awI8b0

+ 19-Ju-16: Faculty Position in Computer Sciences. Universidad Adolfo Ibanez,
  Faculty of Engineering and Sciences. #Job #CompSci 

+ 19-Jul-16: Professor of Computer Science/Technology. Zhejiang University,
  College of Natural Sciences http://bit.ly/2a6On9b #Job #CompSci 

+ 19-Jul-16: PhD fellowship in RNA Bioinformatics http://bit.ly/2a6Olyg

+ 19-Jul-16: PhD position in computational statistics for medical
  imaging. http://bit.ly/2a5bJt6 

+ 15-Jul-16: Lecturer in mathematics (info security) at School of Science, RMIT
  University, Melbourne, Australia http://bit.ly/29APbOR #Job #CompSci  

+ 13-Jul-16: Assistant or Associate Professorship in Theoretical Computer
  Science (tenure-track), Amsterdam. http://bit.ly/29MBMpO #Job #CompSci

+ 09-Jul-16: PhD or postdoc in semantics engineering in Language Designer's
  Workbench project at TU Delft. http://bit.ly/29nN6cL #PhD #PostDoc #CompSci

+ 07-Jul-16: PhD scholarship: Fully automated controller synthesis for UAV
  missions (Munich, Germany) http://bit.ly/29mIXSs #PhD #CompSci 

+ 07-Jul-16: PhD studentship in semantics and verification of heterogeneous
  programs at Queen Mary. http://bit.ly/29qgb75 #PhD #CompSci

+ 02-Jul-16: Full-time developer position opening at Université de Bordeaux for
  Fall 2016 or Fall 2017. http://bit.ly/29ANuS3 #Job #CompSci #Math

+ 02-Jul-16: Postdoc/PhD position at Innopolis University in area of program
  verification. http://bit.ly/29bZoTK #PhD #PostDoc #CompSci

*** Junio de 2016

+ 31-Jun-16: Postdoc position in verification at IMDEA, Madrid
  http://bit.ly/29bxLwm #PostDoc #CompSci

+ 30-Jun-16: Lectureships in Knowledge Representation and Reasoning (and other
  areas of computer science), Cardiff (Wales). http://bit.ly/29bm2h5 #Job
  #CompSci

+ 30-Jun-16: Several Funded PhD Studentships in Computer Science at IMT
  Lucca. http://bit.ly/29blNT9 #PhD #CompSci

+ 30-Jun-16: Lecturer (Teaching & Research) in Computer Science &
  Informatics. Cardiff University. http://bit.ly/296cX6z #Job #CompSci

+ 28-Jun-16: Postdoctoral associate position in London, working with
  Isabelle. http://bit.ly/293qfT6 #PostDoc #IsabelleHOL

+ 28-Jun-16: Postdoctoral researcher in combinatorial optimization at ETH
  Zurich. http://bit.ly/28ZO3n7 #PostDoc #CompSci

+ 27-Jun-16: Postdoc position on formal verification on security. Nanyang
  Technological University http://bit.ly/28VqDPf #PostDoc #CompSci

+ 27-Jun-16: Becas Iberoamérica, Santander Investigación. http://bit.ly/28VqpYp

+ 25-Jun-16: Haskell developer position at Scrive. Stockholm,
  Sweden. http://bit.ly/28SwS8h #Job #Haskell

+ 25-Jun-16: PhD position at VERIMAG, Grenoble, on combinations of Boolean
  reasoning and parametric linear programming. http://bit.ly/28S2rPF #PhD
  #CompSci

+ 25-Jun-16: #Job #Haskell developer @PicusSecurity in Ankara,
  Turkey. http://bit.ly/28RUI3X http://www.picussecurity.com

+ 24-Jun-16: #Job: Haskell Engineer - Machine Learning: Pioneering a new
  approach to the data security problem. Berkeley, California
  http://bit.ly/28UPQNn #Haskell

+ 22-Jun-16: Wrinkl, Inc. is seeking a Haskell Software Engineer for a
  full-time position located in NYC. http://bit.ly/28UTzth #Job #Haskell

+ 21-Jun-16: Jobs at Monash: Lecturer or Senior Lecturer (Data Science). Monash
  University. http://bit.ly/28RxTOJ #Job #DataScience

+ 17-Jun-16: Post doc at IT University of Copenhagen on a project on guarded
  recursion. http://bit.ly/24VfmVc #PostDoc #CompSci

+ 16-Jun-16: PhD position at INRIA Grenoble on formal methods for
  testing. http://bit.ly/1txvAZl #PhD #CompSci

+ 15-Jun-16: Postdoctoral position in epistemic protocol synthesis, Nancy
  (France). http://bit.ly/1PtXxFD #PostDoc #CompSci

+ 15-Jun-16: 2 #DataScience #PostDoc positions with Sune Lehmann in
  Copenhagen. https://t.co/M9FwVg7WpT

+ 14-Jun-16: Two Lectureships (Assistant Professorships) at St Andrews
  http://bit.ly/1YoP9yk #Job #Functional_programming #CompSci 

+ 14-Jun-16: On-site GHC-related Haskell/C opportunity at Positive Technologies
  (Moscow) http://bit.ly/1YoPDV8 #Job #Haskell

+ 13-Jun-16: Postdoctoral positions at Stanford University on the development
  and application of automated reasoning techniques. http://bit.ly/28xLYc3
  #PostDoc #CompSci

+ 13-Jun-16: 2 postdoc positions: Researcher in algorithmics and semantics of
  higher-order computation. Univ. of Oxford http://bit.ly/1tmGwID #PostDoc
  #CompSci

+ 13-Jun-16: Job offer: close-to-industry research position.
  http://bit.ly/1rl9lDO #PostDoc #Type_theory #Formal_methods #Verification

+ 09-Jun-16: One #PhD or #PostDoc position to develop further the theoretical
  foundations of monitorability. Reykjavik Univ. http://bit.ly/1YfCptS #CompSci

+ 09-Jun-16: #Job: Senior Big Data Developer. London, United
  Kingdom. http://bit.ly/1RXPaBU #Scala #BigData

+ 09-Jun-16: Fancy working on big data challenges with #Scala & #Spark to bring
  green energy to more people? - http://hubs.ly/H03c-p00

+ 09-Jun-16: Work with Scala in Dublin to help build a distributed HR
  management platform - http://hubs.ly/H03c-p20 #Job #Scala

+ 09-Jun-16: CircleCI is seeking a Product Engineer for a full-time position
  located in San Francisco or Toronto. http://bit.ly/1YfAzt3 #Job #Clojure

+ 09-Jun-16: Professor Software technology at Utrecht University
  http://bit.ly/1RXNckV #Job #CompSci

+ 08-Jun-16: PhD student position on formal methods for testing of networks of
  controllers, Grenoble (France) http://bit.ly/1X9JHjd #PhD #CompSci

+ 08-Jun-16: Postdoc in formal methods for system-level security at Univ. Lille
  & CNRS, France. http://bit.ly/1X9JCfj #PostDoc #CompSci

+ 07-Jun-16: Jobs in verified refactoring for OCaml and CakeML at the
  University of Kent. http://bit.ly/1RWhtAv #PostDoc #CompSci

+ 07-Jun-16: Postdoc position in type systems at the New Jersey Institute of
  Technology (NYC area) http://bit.ly/1teDmY4 #PostDoc #CompSci

+ 06-Jun-16: Senior Clojure position where you can build a new approach to personal
  finance. http://hubs.ly/H03cmF70 #Clojure

+ 05-Jun-16: Postdoctoral position in machine learning at the University of
  Pennsylvania. http://bit.ly/28czZQZ #PostDoc #CompSci 

+ 05-Jun-16: PhD Position in Machine Learning. AIT Austrian Institute of
  Technology, Department of Technology http://bit.ly/1Uq1T1K #PhD #CompSci

+ 05-Jun-16: PhD Student in Computer Science. University of Innsbruck,
  Department of Computer Science. http://bit.ly/1Uq1FYs #PhD #CompSci

+ 04-Jun-16: Lispjobs: Secure Outcomes, contract Common Lisp programmer
  http://bit.ly/1XqNycC #Job #Common_Lisp 

+ 01-Jun-16: PhD student position in Logic for Multiscale Network Modelling,
  Leeds (England). http://bit.ly/1WZZhOm #PhD #CompSci

+ 01-Jun-16: Associate senior lectureship (4y) in computational linguistics,
  Gothenburg (Sweden). http://bit.ly/1WZZtNq #Job #CompSci

+ 01-Jun-16: Postdoctoral fellowship in security of cyber-physical
  systems. http://bit.ly/1WZZqRZ #PostDoc #CompSci

+ 01-Jun-16: Functional Jobs: Software Engineer (Haskell/Clojure) at Capital
  Match(Full-time) http://bit.ly/1Pm3b1C #Job #Haskell

+ 01-Jun-16: Functional Jobs: CTO (Haskell/Clojure) at Capital Match
  (Full-time) http://bit.ly/1Pm2qWr #Job #Haskell

*** Mayo de 2016

+ 31-May-16: PhD student or postdoctoral position on oligomorphic clones,
  Vienna (Austria). http://bit.ly/22w5VvN #PhD #PostDoc #Logic

+ 30-May-16: Two-year postdoctoral positions at the Institute UC3M-BS of
  Financial Big Data, Univ. Carlos III de Madrid, Spain. http://bit.ly/27YHdrP
  #PostDoc

+ 30-May-16: Semantic systems application architect (KTP associate). Univ. of
  Manchester. http://bit.ly/1U6ZaKD #Job #CompSci

+ 28-May-16: PhD student position in knowledge-based systems, Lisbon
  (Portugal). http://bit.ly/1Wsn8WW #PhD #CompSci 

+ 26-May-16: PhD position at INRIA Grenoble: "Formal proofs for the analysis of
  real-time systems in Coq" http://bit.ly/1qL7uYF #PhD #CompSci #Coq

+ 26-May-16: PhD position at INRIA Grenoble: "Analysis and types for safe
  dynamic software configurations". http://bit.ly/1TLjUvp #PhD #CompSci

+ 26-May-16: PhD position at INRIA Grenoble: "Programming IoT and software
  defined radio with dynamic data-flow models of computation"
  http://bit.ly/1TLkCZF #PhD #CompSci

+ 21-May-16: Funded PhD (3 years) in program analysis at IRIF (Paris,
  France). http://bit.ly/1sIYEg0 #PhD #CompSci

+ 21-May-16: Funded Post-doc positions in program analysis and verification at IRIF
  (Paris, France). http://bit.ly/1sIYzZY #PostDoc #CompSci

+ 21-May-16: Postdoctoral position in stochastic games, Bordeaux
  (France). http://bit.ly/1VemACJ #PostDoc #CompSci

+ 19-May-16: Hiring Haskell engineers at LeapYear, a data security
  company. http://bit.ly/22w6ohy #Job #Haskell 

+ 18-May-16: Target Haskell data scientist job in Sunnyvale, California, United
  States. http://bit.ly/1WEjh98 #Job #Haskell #DataScience

+ 15-May-16: Research associate positions in refactoring functional programs
  and formal verification (for CakeML). Univ. of Kent http://bit.ly/1spwTci
  #Job #CompSci

+ 12-May-16: #PhD (#PostDoc) position in software verification and synthesis at the Max
  Planck Institute for Software Systems http://bit.ly/1WsRBVb #CompSci

+ 12-May-16: Postdoctoral position in logic, Amsterdam (The Netherlands). 
  http://bit.ly/1QZCauY #PostDoc #Logic #CompSci

+ 12-May-16: PhD student position in Algorithms, Bergen (Norway). http://bit.ly/1QZCbz8 
  #PhD #CompSci

+ 10-May-16: PostDocs and PhD positions on the project "Skye: A programming
  language bridging theory and practice for scientific data
  curation". http://bit.ly/27a1c6y

+ 06-May-16: Several postdoctoral and Ph.D. positions at ENS Lyon, France, in the area of
  verification and certification. http://bit.ly/1ZmUUKQ #PhD #PostDoc #CompSci

+ 06-May-16: Two #PhD studentships in the area of correct and efficient programming for
  concurrent and parallel systems. IC, London. http://bit.ly/1ZmQ2FJ #CompSci

+ 06-May-16: Postdoctoral position in Algorithms, TU Munich (Germany). 
  http://bit.ly/1ZmRV5c #PostDoc #CompSci

+ 02-May-16: Verification of randomized algorithms: open PhD/post doc
  position. TUM, Munich http://bit.ly/1VGEYVS #PhD #CompSci #IsabelleHOL

*** Abril de 2016

+ 30-Abr-16: PhD position in formal modelling and verification for high
  assurance at KTH Royal Institute of Technology. http://bit.ly/1SE6FsD 
  #PhD #CompSci

+ 29-Abr-16: Postdoctoral position in mathematical logic, Salerno
  (Italy). http://bit.ly/248n96Y #PostDoc #Logic

+ 29-Abr-16: Postdoctoral or PhD student position in computation with bounded resources,
  Innsbruck (Austria). http://bit.ly/248njv1 #PhD #PostDoc #CompSci

+ 28-Abr-16: Postdoc position in domain-specific languages. Tufts
  University. http://bit.ly/1N2h1p5 #PostDoc #CompSci

+ 26-Abr-16: PhD student position in formal modeling and analysis of security,
  Rennes (France). http://bit.ly/1pArNaF #PhD #CompSci

+ 26-Abr-16: PhD student position in theoretical computer science, Karlsruhe
  (Germany). http://bit.ly/1pArVHo #PhD #CompSci

+ 23-Abr-16: Ph.D. position in security modeling at IRISA in Rennes, France. 
  http://bit.ly/1VJohtd #PhD #CompSci

+ 18-Abr-16: Contract postdoctoral position in biological programming languages at
  Microsoft Research Cambridge. http://bit.ly/1VdQfg4 #PostDoc #CompSci

+ 18-Abr-16: Verification of randomized algorithms in the theorem prover Isabelle: open
  PhD/post doc position at TUM. http://bit.ly/1VdRgVl #PhD #CompSci 

+ 18-Abr-16: Postdoc position in semantics and effects. University of
  Birmingham. http://bit.ly/1VdSgcc #PostDoc #CompSci

+ 14-Abr-16: PostDoc in algorithms and complexity at University of Oxford. 
  http://bit.ly/1ShlDJZ #PostDoc #CompSci

+ 12-Abr-16: Funded PhD on concurrency modelling using ideas from formal
  verification at Univ. of York, UK. http://bit.ly/25Wi1RU #PhD #CompSci

+ 10-Abr-16: PhD student position in on-line privacy using multi-agent systems,
  London (England). http://bit.ly/1S3ulbu #PhD #CompSci

+ 01-Abr-16: Postdoc ad: quantum-computing programming
  languages. http://bit.ly/1SFCzqi #PostDoc #CompSci 

*** Marzo de 2016

+ 31-Mar-16: PhD position in guarded homotopy type theory. 
  http://bit.ly/1TlfvPZ #PhD #CompSci

+ 27-Mar-16: PhD position at LaBRI Bordeaux France. Subject: higher-order
  verification. http://bit.ly/1VOCvaA #PhD #CompSci

+ 20-Mar-16: PhD and Post-Doc positions in formal methods at Chalmers. 
  http://bit.ly/1SaKJ9S #PhD #PosDoc #CompSci 

+ 17-Mar-16: 2 Ph.D positions on Formal Methods for Rule-based agent safety and
  concurrent system analysis (U. of Oslo). http://bit.ly/1LtAnTj #PhD #CompSci

+ 06-Mar-16: PhD studentship on "Declarative Programming for Data Science"
  http://bit.ly/1U3rbX1 #PhD #CompSci #DP #DataScience

*** Febrero de 2016

+ 26-Feb-16: Two postdoc positions in reasoning about concurrent and distributed
  systems. Imperial College London. http://bit.ly/1QlEDAN

+ 23-Feb-16: 4-year PhD studentship on "Declarative Programming for Data
  Science", University of Edinburgh. http://bit.ly/1OrL7Mh #CompSci #PhD

+ 23-Feb-16: PhD and Post-Doc positions in formal methods and security,
  Chalmers University of Technology. http://bit.ly/1RkdZL0 #PhD #CompSci

+ 18-Feb-16: Postdoctoral Research Fellow in Artificial Intelligence. Western
  Sydney University. http://bit.ly/1U9VjAh #PostDoc #CompSci

+ 15-Feb-16: Postdoc position at Tulane on the "Semantics, formal reasoning,
  and tool support for quantum programming" project. http://bit.ly/1KQyEXF #CompSci

+ 11-Feb-16: Phd/PostDoc positions in formal methods for distributed systems at
  University Paris Diderot, France. http://bit.ly/1WglkfP #PostDoc #CompSci

+ 03-Feb-16: Postdoctoral position in functional, constraint and/or logic programming at
  KU Leuven. http://bit.ly/1PSet7A #PostDoc #CompSci

*** Enero de 2016

+ 20-Ene-16: Postdoc position on hardware verification at NTU
  Singapore. http://bit.ly/1ltVFDH #PostDoc #CompSci 

+ 20-Ene-16: Postdoc position on security protocol verification at NTU
  Singapore. http://bit.ly/1ltVUP1 #PostDoc #CompSci 

+ 15-Ene-16: Postdoctoral and PhD positions in LFCS on graph databases,
  provenance, and programming languages. http://bit.ly/1Zztq9z #PostDoc #CompSci

+ 12-Ene-16: Postdoc position at Penn on the DeepSpec
  project. http://bit.ly/1ZhC4Ux #PostDoc #CompSci

+ 09-Ene-16: ERC project "RustBelt" on foundations for Rust -- Postdoc and PhD
  positions available! http://bit.ly/1Pk6osr #PostDoc #PhD #CompSci

+ 07-Ene-16: Postdocs at Tulane on semantics of quantum programming
  languages. http://bit.ly/1SCm8fI #PostDoc #CompSci 

 



