#+TITLE: Ofertas de trabajo de interés para el MULCIA 

En esta página se recopilan las ofertas de trabajo de interés para los
estudiantes del [[http://master.cs.us.es/M%C3%A1ster_Universitario_en_L%C3%B3gica,_Computaci%C3%B3n_e_Inteligencia_Artificial][Máster Universitario en Lógica, Computación e Inteligencia
Artificial]] de la [[http://www.us.es][Universidad de Sevilla]].

Están en orden cronológico inverso por la fecha de su publicación en [[https://twitter.com/Jose_A_Alonso][Twitter]] o
en la [[https://listas.us.es/mailman/listinfo/master_mulcia][lista de correo del Máster]].

** 2018

* Septiembre 2018

+ 10-Sep-18: Postdoctoral position in biological programming languages,
  Microsoft Research, Cambridge, UK. http://bit.ly/2wZHPRz #PostDoc
  #CompSci 

+ 09-Sep-18: Postdoc position in machine learning, programming languages
  and software engineering at the IT University of Copenhagen.
  http://bit.ly/2CI6no6 #PostDoc #CompSci 

+ 09-Sep-18: PhD positions in the INSIGHT project (Program Repair with
  static insights”) at the IT University of Copenhagen.
  http://bit.ly/2CI6IHo #PhD #CompSci  

+ 04-Sep-18: Research Fellow in Verification at the University of
  Surrey, UK. http://bit.ly/2wEZEWN #PostDoc #CompSci 

+ 03-Sep-18: The Chair of Programming Methodology at ETH Zurich is
  recruiting PhD students and post-docs for several projects on program
  verification and static program analysis for program correctness and
  security. http://bit.ly/2NK3BzW #PhD #PostDoc #CompSci 

+ 01-Sep-18: Postdoc vacancy in "Quantum circuit optimisation and
  graphical calculus" at Radboud University,
  Nijmegen. http://bit.ly/2PVnp4H #PostDoc #CompSci 

+ 01-Sep-18: Postdoc position in Safety control and energy efficiency
  for embedded systems. Aarhus University. http://bit.ly/2osUHM7
  #PostDoc #CompSci 

+ 01-Sep-18: PhD openings in the Security and Privacy group at TU
  Wien. http://bit.ly/2PW8SpK #PhD #CompSci 

+ 01-Sep-18: PhD position on "Concurrency, Logic, and Type
  Systems". University of Groningen. http://bit.ly/2orXXaD #PhD #CompSci 

*** Agosto 2018

+ 30-Ago-18: Post-doc and researcher positions in Tallinn in the areas
  of Trustworthy Software Technologies, Hardware Security and Trust,
  Internet of Intelligent Things. http://bit.ly/2wzna6u #PostDoc
  #CompSci 

+ 30-Ago-18: A research grant position for one year in the field of
  Computer Aided Formal Reasoning is available at the University of
  Udine. http://bit.ly/2wxlw5C  #PostDoc #CompSci 

+ 24-Ago-18: Two phd/post-doc positions: Formalization and verification
  of traffic rules for automated vehicles. http://bit.ly/2o6cSqN
  #PostDoc #CompSci 

+ 21-Ago-18: Postdoctoral & development positions on PL for data
  curation at Edinburgh LFCS. http://bit.ly/2Mtz78Z #PostDoc #CompSci 

+ 21-Ago-18: Postdoc/Engineer positions (formal methods and quantum
  computation) at LRI - U. Paris Saclay. http://bit.ly/2nWnRmI #PostDoc
  #CompSci 

+ 18-Ago-18: PhD thesis position on formal proofs and programming
  languages at Siemens Mobility, France. http://bit.ly/2PcZuO5 #PhD
  #CompSci 

+ 15-Ago-18: Postdoc and PhD positions. Center for Advanced Software
  Analysis, Aarhus University. http://bit.ly/2wcJX8m #PostDoc #PhD
  #CompSci 

+ 09-Ago-18: PhD opportunities at the Australian National
  University. http://bit.ly/2MfeE6A #PhD #CompSci #Logic 

+ 09-Ago-18: PhD studentship in logic and verification at University
  College London. http://bit.ly/2OVZORd #PhD #CompSci 

+ 09-Ago-18: Full-time position at Tesla, Inc.: Software Engineer -
  Functional Programming. http://bit.ly/2Ma9PLP #Job #CompSci
  #FunctionalProgramming  

+ 05-Ago-18: PhD position in Software Lab at TU
  Darmstadt. http://bit.ly/2MjdjbX #PhD #CompSci  

+ 05-Ago-18: 2 PhD fellows in functional technology for high-performance
  architectures. http://bit.ly/2Mjd2pr #PhD #CompSci 

*** Julio 2018

+ 28-Jul-18: PhD Position on the formalization of automated reasoning in
  Isabelle/HOL. http://bit.ly/2NOBgIq #PhD #CompSci 

+ 28-Jul-18: PhD and post-doc positions on formal methods for voting
  systems, University of Luxembourg. http://bit.ly/2LZlw4Z #PhD #PostDoc
  #CompSci 

+ 26-Jul-18: Postdoc position in computational geometry at the
  University of Sydney. http://bit.ly/2LpWQGd #PostDoc #CompSci 

+ 25-Jul-18: Two PhD positions in program verification at KU Leuven.
  http://bit.ly/2NJhhKW #PhD #CompSci 

+ 25-Jul-18: Seeking postdoc for information-flow type systems at the
  hardware/OS level. Cornell University. http://bit.ly/2NJ3F2x #PostDoc
  #CompSci 

+ 23-Jul-18: PhD position on `Quantum annealing for SAT solving' in
  Trento. http://bit.ly/2LFZeEZ #PhD #CompSci 

+ 19-Jul-18: Postdoctoral Position in Machine Learning & Computer
  Algebra. http://bit.ly/2uBypv6 #PostDoc #CompSci  

+ 09-Jul-18: PhD Position on the formalization of automated reasoning in
  Isabelle. http://bit.ly/2NEbLtR #PhD #CompSci 

+ 09-Jul-18: PhD Research project on big data monitoring. ETH Zürich,
  Switzerland http://bit.ly/2KW10of #PhD #CompSci 

+ 09-Jul-18: PhD Research project on privacy, data protection, and
  access control. ETH Zürich, Switzerland http://bit.ly/2KW10of #PhD
  #CompSci  

+ 09-Jul-18: Open Positions for Ph.D. candidates and Postdocs in
  information-flow security and side-channel analysis. TU Darmstadt,
  Germany http://bit.ly/2NExHFc #PhD #PostDoc #CompSci 

+ 09-Jul-18: Postdoctoral positions in formal methods. Stanford
  University, USA. http://bit.ly/2Nzo0rM #PostDoc #CompSci 

+ 09-Jul-18: PhD Position: Leveraging automatic deduction for
  verification. Loria and Inria Nancy, France http://bit.ly/2NCDPy3 #PhD
  #CompSci 

+ 09-Jul-18: Postdoc Position: Verification of autonomous robots. York,
  UK. http://bit.ly/2KYli0o #PostDoc #CompSci 

+ 09-Jul-18: Post-doctoral researchers wanted for Coq developments
  (certified distributed algorithms; certified compiler). Grenoble,
  France http://bit.ly/2KXdPeS #PostDoc #CompSci 

+ 09-Jul-18: PhD position in complex networks and knowledge graphs
  (Research Assistant). University of Kassel,
  Germany. http://bit.ly/2NA4hbi #PhD #CompSci 

+ 07-Jul-18: Postdoc position in "Reasoning and programming with
  infinite data-objects" project at Paris Diderot
  University. http://bit.ly/2u0mA1r #PostDoc #CompSci 

+ 07-Jul-18: PhD fellow in probabilistic programming and protein
  structure prediction. http://bit.ly/2tWVLLx #PhD #CompSci

+ 06-Jul-18: Haskell developer at Henry in Stockholm. 
  http://bit.ly/2u8SfwN #Job #Haskell 

+ 06-Jul-18: PhD position in ICT in Trento on "Quantum annealing for SAT
  solving". http://bit.ly/2zd0yh1 #PhD #CompSci 

+ 06-Jul-18: Research assistant/ associate in disciplined approximate
  arithmetic. Imperial College London. http://bit.ly/2ubgham #Job
  #CompSci 

+ 06-Jul-18: Postdoc position at Chalmers in the area of software
  variability. University of Gothenburg. http://bit.ly/2ub4JnJ #PostDoc
  #CompSci 

+ 06-Jul-18: PhD positions in software engineering/formal
  methods. Università della Svizzera italiana (USI), Lugano,
  Switzerland. http://bit.ly/2lZ8V6o #PhD #CompSci 

+ 04-Jul-18: Postdoc vacancy: Homotopy type theory and probabilistic
  programming. Aarhus University, Denmark. http://bit.ly/2z8sSAS
  #PostDoc #CompSci 

+ 04-Jul-18: PhD position: Type theory, probabilistic computation and
  computer-aided cryptography proofs. Aarhus University,
  Denmark. http://bit.ly/2u5A1w4 #PhD #CompSci  

+ 03-Jul-18: PhD position: Unifying correctness for communicating
  software. University of Groningen, The Netherlands. 
  http://bit.ly/2KrFqst #PhD #CompSci 

*** Junio 2018

+ 30-Jun-18: Open Ph.D. position in Privacy and Access Control at ETH
  Zurich. http://bit.ly/2IAF1y9 #PhD #CompSci 

+ 24-Jun-18: PhD openings in the Security and Privacy group at TU
  Wien. http://bit.ly/2Kgbewf #PhD #CompSci 

+ 24-Jun-18: PhD student position in logic and verification, London
  (England). http://bit.ly/2Kjtzs8 #PhD #CompSci #Logic

+ 20-Jun-18: PhD Student in software security and formal
  methods. http://bit.ly/2JUvBmo #PhD #CompSci 

+ 20-Jun-18: PostDoc at Inria, Paris, on validation and synthesis of
  DWARF debugging information. http://bit.ly/2MEJyml #PostDoc #CompSci

+ 20-Jun-18: Fully funded EPSRC iCASE PhD scholarship: "Verification of
  real time systems" at Swansea University. http://bit.ly/2MDEwXr #PhD
  #CompSci

+ 16-Jun-18: Two Post-doc Research Fellowships at NOVA LINCS/NOVA
  University of Lisbon and OutSystems collaborative
  laboratory. http://bit.ly/2sZsyiE #PostDoc #CompSci 

+ 16-Jun-18: Postdoc positions in formal methods at Stanford
  University. http://bit.ly/2Mt4kFo #PostDoc #CompSci 

+ 16-Jun-18: Graduiertenkolleg "Facets of Complexity": Seven
  Ph.D. positions, starting September 2018, for three
  years. http://bit.ly/2td4dox #PhD #CompSci 

+ 16-Jun-18: PhD studentship in Logic & Verification at
  UCL. http://bit.ly/2tbXUl9 #PhD #CompSci 

+ 16-Jun-18: Fully-funded PhD studentship at University of Kent for the
  project "Specification and verification of C++ data structure
  libraries". http://bit.ly/2py3n52 #PhD #CompSci   

+ 16-Jun-18: Research Associate position on Verification of Linear
  Dynamical Systems, Oxford(England). http://bit.ly/2LWJC0l #PostDoc
  #CompSci 

+ 16-Jun-18: Fully-Funded Ph.D. Studentship in Analysis of Concurrent
  Systems. University of Warsaw http://bit.ly/2LTRjVf #PhD #CompSci 

+ 05-Jun-18: Nuevas oportunidades del Consejo Europeo de Investigación
  Nuclear (CERN) para investigadores y estudiantes de la Universidad de
  Sevilla. http://bit.ly/2LTQcF3 #Job #CompSci 

+ 05-Jun-18: Research Associate position on verification of linear
  dynamical systems, Oxford (England). http://bit.ly/2LWJC0l #PostDoc
  #CompSci 

+ 05-Jun-18: Postdoctoral position on "optimal proofs", Utrecht (The
  Netherlands). http://bit.ly/2M0GjFn #PostDoc #Logic 

+ 05-Jun-18: PhD student position in analysis of concurrent systems,
  Warsaw (Poland). http://bit.ly/2LTRjVf #PhD #CompSci 

+ 05-Jun-18: PhD student position in computational (psycho)linguistics,
  Stuttgart (Germany). http://bit.ly/2M2VZrE #PhD #CompSci  

+ 05-Jun-18: PhD student position in computational semantics, Utrecht
  (The Netherlands). http://bit.ly/2LWKhPn #PhD #CompSci   

+ 05-Jun-18: PhD student position in modelling and verification of
  software systems, London (England). http://bit.ly/2LXfRN0 #PhD
  #CompSci     

+ 05-Jun-18: PhD student position in formal semantics, Utrecht (The
  Netherlands). http://bit.ly/2IHpu0s #PhD #CompSci 

+ 05-Jun-18: Open postdoc position on higher-order model
  checking. University of Tokyo, Japan. http://bit.ly/2LXO52S #PostDoc
  #CompSci 

+ 05-Jun-18: VeTSS PhD Scholarship Programme on Session Types and
  Programming Languages. Imperial College London. http://bit.ly/2LYdcCI
  #PhD_CompSci 

+ 05-Jun-18: Postdoc at Imperial on the IRIS project, on "Compositional
  reasoning for high-assurance many-core software". http://bit.ly/2LYvALX 
  #PostDoc #CompSci 

+ 05-Jun-18: PL Research positions at Facebook Languages Research
  (FLaRe). http://bit.ly/2M0u3oD #PostDoc #CompSci 

*** Mayo 2018

+ 28-May-18: Categorical Informatics, a data
  modeling/integration/migration company pioneering a new approach to
  data based on category theory, is looking to recruit an initial
  technical staff. http://bit.ly/2LyxC54 #Job #CompSci  

+ 26-May-18: Data Scientist / Spatial Data Scientist: 2 x Fixed-Term
  appointments (4 years). University of Wollongong (UOW) - New South
  Wales, Australia  http://bit.ly/2ISIPvm #Job #CompSci #DataScience 

+ 26-May-18: Research Associate in Medical Machine Learning. Lancaster
  University. http://bit.ly/2xl36ZA #PostDoc #CompSci #MachineLearning 

+ 26-May-18: Formal verification position at Toyota ITC, Mountain
  View. http://bit.ly/2IMOKGz #PostDoc #CompSci 

+ 26-May-18: Open Ph.D. position in Runtime Verification and Monitoring
  at ETH Zürich. http://bit.ly/2IMVYGn #PhD #CompSci 

+ 26-May-18: Two Research Associate Positions (Post-doc, Full Time,
  Fixed Term) at Imperial College London. http://bit.ly/2IPUsDm #PostDoc
  #CompSci 

+ 22-May-18: Postdoc on using machine learning to make runtime
  verification more efficient. University of Kent. http://bit.ly/2LkHJuj
  #PostDoc #CompSci 

+ 22-May-18: The Security Group at Arm Research is seeking a Formal
  Methods Intern to work on the application of software verification
  technology to cryptographic code. http://bit.ly/2IB86OM #PhD #CompSci 

+ 22-May-18: 18 PhD positions in Computer Science and System Engineering
  at University of Verona. http://bit.ly/2ID7B2A #PhD #CompSci

+ 22-May-18: PhD student position in formal semantics, Utrecht (The
  Netherlands). http://bit.ly/2IHpu0s #PhD #CompSci 

+ 21-May-18: PhD position in KRR at Artois University, France. The goal
  of the thesis is to investigate and develop non-monotonic logic-based
  formalisms for the specification and verification of
  exception-tolerant systems. http://bit.ly/2IztRyv #PhD #CompSci 

+ 18-May-18: Ph.D. Fellowship in unconventional computation. Norwegian
  University of Science and Technology (NTNU). http://bit.ly/2GvE6hd
  #PhD #CompSci 

+ 18-May-18: Machine Learning Engineer. Think
  Silicon. http://bit.ly/2GuHLfe #Job #CompSci 

+ 18-May-18: High performance computing in medical imaging. University
  of Cordoba, Spain. http://bit.ly/2IqMEMp #PostDoc #CompSci 

+ 18-May-18: Research Assistant/Research Associate, ECOSCALE H2020
  project (two posts available). University of
  Manchester. http://bit.ly/2rRyKbP #PhD #PostDoc #CompSci 

+ 17-May-18: PhD studentship in formal methods & verification at
  University College London. http://bit.ly/2IooP80 #PhD #CompSci 

+ 17-May-18: Tezos is hiring! Tezos is a self-governing blockchain and
  smart-contract platform written in OCaml. http://bit.ly/2rOwG3C #PhD
  #PostDoc #CompSci #FunctionalProgramming 

+ 14-May-18: Research Fellow in geometric topology, topological quantum
  field theory and applications to quantum computing. http://bit.ly/2KZ0KSL 
  #PostDoc #Math #CompSci 

+ 13-May-18: Postdoc in formal verification for formal contracts
  co-funded by Deon Digital and the Danish Innovation
  Foundation. University of Copenhagen http://bit.ly/2KToqI5 #PostDoc
  #CompSci 

+ 09-May-18: Research positions in logic & verification at UCL
  (University College London), London, UK. http://bit.ly/2KPkRCC
  #PostDoc #CompSci 

+ 07-May-18: PhD fellows in natural language processing and machine
  learning University of Copenhagen. http://bit.ly/2FPVuND #PhD #CompSci 

+ 07-May-18: PhD position in dominance based fuzzy rough set models for
  preference learning in ordinal classification. Ghent
  University. http://bit.ly/2FRCzBY #PhD #CompSci  

+ 07-May-18: PhD position in fuzzy rough set models for machine learning
  and sentiment analysis. Ghent University. http://bit.ly/2jz0vkL #PhD
  #CompSci   

+ 07-May-18: Research fellow in machine learning. University of
  Warwick. http://bit.ly/2FQpmcI #PostDoc #CompSci 

+ 07-May-18: Open positions in crypto/security at IT University of
  Copenhagen. http://bit.ly/2jCwn8n #PostDoc #CompSci  

+ 07-May-18: PhD positions in PL and distributed systems at IMDEA,
  Madrid. http://bit.ly/2FRXe8N #PhD #CompSci

+ 07-May-18: PhD student position on quantitative & qualitative analysis
  of multi-player games, Stockholm (Sweden). http://bit.ly/2FOWjGd #PhD
  #CompSci 

+ 05-May-18: 18 PhD positions at 7 Swedish universities focusing on the
  mathematical foundations of artificial intelligence. http://bit.ly/2FLn52i 
  #PhD #CompSci #Math #AI 

*** Abril 2018

+ 30-Abr-18: PhD studentship on the CakeML project. The position is part
  of the "Building verified applications in CakeML" (University of Kent)
  http://bit.ly/2I8CO0u #PhD #CompSci 

+ 30-Abr-18: Postdoctoral position on "The implicit commitment of
  mathematical theories through intensional notions", Pisa
  (Italy). http://bit.ly/2r7QTBW #PostDoc #Logic 

+ 30-Abr-18: PhD-student in mathematics within the WASP project
  Mathematics for AI on quantitative & qualitative analysis of
  multi-player games, Stockholm (Sweden) http://bit.ly/2I1KxNR #PhD
  #CompSci

+ 30-Abr-18: PhD student position in the history and philosophy of
  programming, Lille (France). http://bit.ly/2w8vX2H #PhD #CompSci 

+ 25-Abr-18: PhD position in logic and its application to program and
  systems verification at UCL. http://bit.ly/2HwqQuh #PhD #CompSci 

+ 22-Abr-18: PhD in CS focused on SAT solving at KTH Royal Institute of
  Technology. http://bit.ly/2vzNj8b #PhD #CompSci  

+ 21-Abr-18: Doctoral student in system security and formal methods. KTH
  Royal Institute of Technology. http://bit.ly/2HRbnpA #PhD #CompSci

+ 21-Abr-18: Senior Research Associate on power of algorithms in
  discrete optimisation. Pxford University. http://bit.ly/2F49cMt
  #PostDoc #CompSci 

+ 19-Abr-18: Postdoctoral position in computational social choice /
  algorithmic game theory, Berlin (Germany). http://bit.ly/2HxmvtP
  #PostDoc #CompSci 

+ 19-Abr-18: PhD position in "Foundations of interactive democracy",
  Berlin (Germany). http://bit.ly/2HAm0zl #PostDoc #CompSci 

+ 17-Abr-18: The CELTIQUE team has a PhD position available on the
  definition of a rule format to specify formal semantics and derive
  certified static analyzers in Coq. http://bit.ly/2H5P6ax #PhD #CompSci
  #Coq 

+ 17-Abr-18: Postdoc and PhD positions in verification at IMDEA (Madrid)
  in the areas of software verification of concurrent programs,
  separation logic, and language-based security. http://bit.ly/2H65p72
  #PhD #PostDoc #CompSci  

+ 17-Abr-a8: Three PhD student positions in Cognitive Science &
  Artificial Intelligence, Tilburg (The Netherlands). http://bit.ly/2H68WlY 
  #PhD #CompSci 

+ 16-Abr-18: PhD student position in concurrency theory, Groningen (The
  Netherlands). http://bit.ly/2qCrNuz #PhD #CompSci 

+ 16-Abr-18: Postdoctoral position in nonstandard methods in Ramsey
  Theory, Vienna (Austria). http://bit.ly/2HnYmGh #PostDoc #Logic

+ 10-Abr-18: The programming languages group at University of Freiburg,
  Germany, has an opening for a research assistant to work on a
  DFG-funded project to create a version of OCaml with linear types and
  session types to start on July 1, 2018. http://bit.ly/2uYBp7s #PostDoc
  #CompSci 

+ 10-Abr-18: Postdoc in security protocols and formal
  methods. University of Luxembourg. http://bit.ly/2Hp3k30 #PostDoc
  #CompSci 

+ 10-Abr-18: PostDoc position on formally secure compilation at Inria
  Paris. http://bit.ly/2v2qfi3 #PostDoc #CompSci

+ 07-Abr-18: PhD student scholarships in logic and related fields,
  Canberra (Australia). http://bit.ly/2HiNeI0 #PhD #CompSci 

+ 07-Abr-18: PhD student position in formal methods, Konstanz
  (Germany). http://bit.ly/2GEVAIX #PhD #CompSci 

+ 07-Abr-18: Postdoc position in Logic, Gothenburg
  (Sweden). http://bit.ly/2FLrH9W #PostDoc #Logic 

+ 07-Abr-18: Postdoctoral position in machine learning + program
  synthesis at Rice University. http://bit.ly/2HgNLu1 #PostDoc #CompSci 

*** Marzo 2018

+ 29-Mar-18: PhD position on "Fault localization and explanation for
  concurrent programs" available at Inria Grenoble (France). http://bit.ly/2GEzwl6 #PhD #CompSci 

+ 29-Mar-18: PhD student positions in symmetry in computational
  complexity, Prague (Czech Republic). http://bit.ly/2GngiNv #PhD #CompSci 

+ 29-Mar-18: Twenty-month Postdoctoral Fellowship in the context of the
  ANR-DFG research program "Formalism, formalisation, intuition, and
  understanding in mathematics". Nancy / Paris (France)
  http://bit.ly/2GlTPQS #PostDoc #CompSci

+ 28-Mart-18: Post-doc and PhD positions on program analysis and code
  optimisation using machine learning. http://bit.ly/2usDSGV #PhD
  #PostDoc #CompSci

+ 28-Mar-18: Postdoctoral and Ph.D. positions on software security at
  Uppsala University. http://bit.ly/2J1X69C #PhD #PostDoc #CompSci 

+ 28-Mar-18: PhD positions in theoretical computer science at KTH Royal
  Institute of Technology http://bit.ly/2uwFOP0 #PhD #CompSci 

+ 28-Mar-18: Postdoc positions in theoretical computer science at KTH
  Royal Institute of Technology http://bit.ly/2utnd67 #PostDoc #CompSci

+ 28-Mar-18: PhD Scholarships in Logic and Verification at the
  Australian National University. http://bit.ly/2uwqD8u #PhD #CompSci 

+ 28-Mar-18: Haskell development job with Well-Typed. 
  http://bit.ly/2urKVzR #Job #Haskell 

+ 24-Mar-18: ESRC-funded PhD studentship at University of Edinburgh for
  the project "Interpretable scoring models for understanding household
  financial distress". http://bit.ly/2py3n52 #PhD #CompSci 

+ 24-Mar-18: Postdoctoral Fellowship in Symbolic Computation in the
  areas of the gran "AF:Small: Symbolic Computation with Certificates,
  Sparsity and Error Correction" http://bit.ly/2DReTws #PostDoc #CompSci

+ 24-Mar-18: PhD studentship on Automated Black-box Verification of
  Networking Systems at University College London. http://bit.ly/2py4rG4
  #PhD #CompSci 

+ 24-Mar-18: Multiple positions at FAU Erlangen/Nürnberg for the
  following projects: "Argumentation logics manager & argument context
  graph" and "Open digital research environment toolkit for the
  advancement of Mathematics" http://bit.ly/2pBmScN #PhD #PostDoc
  #CompSci 

+ 24-Mar-18: Postdoctoral research position in cybersecurity at Inria
  Rennes, Brittany, France. http://bit.ly/2pAxB7i #PostDoc #CompSci 

+ 24-Mar-18: A post-doctoral position on the formal proof of the GNU
  MPFR library. http://bit.ly/2pBoDqp #PostDoc #CompSci 

+ 24-Mar-18: Obsidian Systems is looking for developers to work on
  full-stack Haskell web and mobile applications. http://bit.ly/2pzPhAa
  #Job #Haskell

+ 22-Mar-18: Assistant Professor in Computer Science directed towards
  Logic of Programs. Stockholm University, Sweden http://bit.ly/2pvXwgt
  #Job #CompSci 

+ 22-Mar-18: Formal methods internship at Toyota ITC. http://bit.ly/2pvKzTM 
  #PhD #CompSci

+ 22-Mar-18: Postdoctoral position in "A new dawn of intuitionism",
  Leeds (England). http://bit.ly/2DLR2OO #PostDoc #Logic 

+ 17-Mar-18: Data61 seeking junior proof  engineers. http://bit.ly/2GBYy1F 
  #Job #CompSci 

+ 17-Mar-18: Data61 seeking senior proof engineers. http://bit.ly/2FNrD97 
  #Job #CompSci  

+ 17-Mar-18: Haskell position in evolutionary bioinformatics at American
  Museum of Natural History (New York). http://bit.ly/2FH1qgt #Job
  #Haskell 

+ 15-Mar-18: Post-doc on formal proofs about the floating-point
  evaluation of polynomials in Orsay, France. http://bit.ly/2FCPFaN
  #PostDoc #CompSci  

+ 13-Mar-18: The University of Leeds School of Mathematics is looking
  for a Research Fellow to join our project "A new dawn of
  intuitionism," which seeks to address contemporary foundational
  concerns from the intuitionistic point of view. http://bit.ly/2FxhSA5
  #PostDoc #Logic #CompSci 

+ 09-Mar-18: Becas para cursar Másteres Universitarios en la Universidad
  de Sevilla 2018/2019. http://bit.ly/2GeZ4ml

+ 09-Mar-18: IOHK is looking for a talented, functional compiler
  engineer. The candidate will be responsible for designing and
  implementing functional programming languages for next-generation
  blockchain smart contract systems. http://bit.ly/2FxgNEh #Job
  #FunctionalProgramming #Haskell

+ 08-Mar-18: QFPL (Queensland Functional Programming Lab) is hiring 5
  functional programmers in Brisbane, Australia. http://bit.ly/2FsxQr3
  #Job #Haskell 

+ 08-Mar-18: The Institute of Computer Science of the Czech Academy of
  Sciences (ICS), Prague, Czech Republic, is seeking a postdoctoral
  researcher to complement the team for the project "Non-classical
  logical models of information  dynamics". http://bit.ly/2G9KJYl
  #PosDoc #CompSci 

+ 08-Mar-18: Professor Kaltofen's NSF grant "AF: Small: Symbolic
  Computation with Certificates, Sparsity and Error Correction" funds a
  2-years postdoc to perform research in the areas of the the grant.
  North Carolina State University http://bit.ly/2FoWf0w #PosDoc #CompSci 

+ 08-Mar-18: The Center for Computation and Technology of Louisiana
  State University is looking for a Postdoc in the field of
  Combinatorial Optimization. http://bit.ly/2G6fNrM #PosDoc #CompSci 

+ 06-Mar-18: Postdoc at the Center for algorithms and machine learning
  at Indiana University Bloomington. http://bit.ly/2FX246D #PostDoc
  #CompSci 

+ 05-Mar-18: The Microsoft Research-INRIA Joint Centre is offering a
  24-month position for a research engineer to contribute to the design
  and further development of the TLA+ Proof System. http://bit.ly/2D2AYYx 
  #PostDoc #CompSci 

+ 05-May-18: Post-doctoral position: Compiling recursive functions to
  inductive definition in Coq. http://bit.ly/2FWGGhU #PostDoc #CompSci 

+ 05-Mar-18: Two postdoc positions at Imperial: “Security analysis for
  graphics drivers”, and “Programming language and system support for
  high-performance data processing” http://bit.ly/2CYAEKx #PostDoc
  #CompSci 

+ 05-Mar-18: 16 PhD Positions on Logical Methods in Computer
  Science. The doctoral positions are funded for a period of 4 years
  according to the funding scheme of the Austrian Science
  Fund. http://bit.ly/2CYCWJE #PhD #CompSci #Logic 


+ 01-Mar-18: Software engineer job situated in a PL research group. The
  work will be largely about sandboxing, containerization, and other low
  level systems stuff, but all the high-level software in the group is
  written in Haskell. http://bit.ly/2F2K1dO #Job #CompSci #Haskell 

+ 01-Mar-18: PhD student position in computational social choice,
  Amsterdam (The Netherlands). http://bit.ly/2F4oamh #PhD #CompSci 

+ 01-Mar-18: PhD position in computational linguistics, Utrecht (The
  Netherlands). http://bit.ly/2FGmgcO #PhD #CompSci 

*** Febrero 2018

+ 27-Feb-18: Postdoctoral research at Stanford University under
  Professor Clark Barrett. http://bit.ly/2F1aNTQ #PostDoc #CompSci 

+ 26-Feb-18: PhD student positions in modal logic for granularity and
  spatial knowledge representation, Leeds (England). 
  http://bit.ly/2FA79S3 #PhD #Logic

+ 26-Feb-18: Postdoctoral fellowship in logic in CS, Groningen (The
  Netherlands). http://bit.ly/2FyQzSJ #PostDoc #Logic #CompSci 

+ 24-Feb-18: Backend Haskell engineer job at Holmusk in
  Singapore. http://bit.ly/2FyYLlU #Job #Haskell

+ 23-Feb-18: Postdoc at Department of Computer Science, University of
  Copenhagen. The project focuses on algorithms theory for graph
  problems. http://bit.ly/2FqyuGm #PostDoc #CompSci 

+ 23-Feb-18: Postdoc in formal methods / game theory / machine learning
  for controller synthesis at UMONS, Belgium. http://bit.ly/2FsnEiQ
  #PostDoc #CompSci  

+ 23-Feb-18: PhD positions in Theoretical Computer Science at ETH
  Zürich. http://bit.ly/2EQ3iyX #PhD #CompSci

+ 23-Feb-18: The IT University of Copenhagen seeks PhD student to the
  type theories for reactive programming project. http://bit.ly/2EQoUeC
  #PhD #CompSci  

+ 23-Feb-18: PhD position in formal methods for security. Technical
  University of Denmark. http://bit.ly/2EOE0BA #PhD #CompSci

+ 21-Feb-18: Postdoctoral researcher in programming languages and
  machine learning n the Computer Science & Engineering department at
  Penn State. http://bit.ly/2GzY2QO #PostDoc #CompSci 

+ 21-Feb-18: Tsuru Capital is hiring Haskellers! Full-time and interns
  in Tokyo, Japan: http://bit.ly/2HyIwFU #Job #Haskell 

+ 21-Feb-18: The National Institute of Aerospace (NIA), located in
  Hampton, Virginia, has an opening for the position of Research
  Scientist to work on research and development of theorem proving
  technology for the formal verification of autonomous
  systems. http://bit.ly/2GAeKPF #Job #CompSci #ITP 

+ 17-Feb-18: PhD and Postdoc positions at IRISA/Inria Rennes: Formal
  verification with Coq. http://bit.ly/2Gmx1Qy #PhD #PostDoc #CompSci 

+ 15-Feb-18: PhD position at the University of Birmingham: higher
  categories, quantum computing, formal proof. http://bit.ly/2HiTS0z
  #PhD #CompSci  

+ 15-Feb-18: Doctoral student funding at Boston University: formal
  methods for cryptography. http://bit.ly/2Ggp6nK #PhD #CompSci 

+ 15-Feb-18: PhD position on high-level synthesis of neural networks for FPGAS
  with LIFT. http://bit.ly/2HhAWiI #PhD #CompSci 

+ 15-Feb-18: The Centre for Quantum Technologies at the National University of
  Singapore invites applications for a Postdoctoral Research Fellowship in its
  Computer Science Group in the broad area of quantum-safe
  cryptography. http://bit.ly/2Gf64ya #PostDoc #CompSci  

+ 15-Feb-18: The algorithms group in Duke Computer Science invites applications
  for a postdoctoral position. Candidates in geometric algorithms and data
  structures are of particular interest. http://bit.ly/2HhPIGg #PostDoc
  #CompSci   

+ 10-Feb-18: Post-doc position in programming language theory / practice,
  computing science, University of Glasgow. http://bit.ly/2G59LGJ #PostDoc
  #CompSci 

+ 08-Feb-18: PhD position: Software engineering, formal methods, highly
  configurable systems (Gothenburg, Sweden). http://bit.ly/2GZzCB3 #PhD
  #CompSci 

+ 07-Feb-18: Sr. formal verification engineer careers at Intel in Hillsboro,
  OR. http://intel.ly/2FUIzuh #Job #CompSci 

+ 07-Feb-18: Postdocs to work in a small, agile team at NASA Ames Research Park
  in Silicon Valley on the multi-year QUASAR project (Quantifiable Assurance
  Cases for Trusted Autonomy), part of the US Defense  Advanced Research
  Projects Agency (DARPA) Assured Autonomy research
  program. http://bit.ly/2GXfFem #PostDoc #CompSci 

+ 06-Feb-18: ERC funded RA (PostDoc) position in formal verification at
  University of Leicester. http://bit.ly/2GTylf1 #PostDoc #CompSci 

+ 05-Feb-18: Multiple PhD and Postdoc positions, security and privacy group, TU
  Wien, Austria. http://bit.ly/2sg6oe7 #PhD #PostDoc #CompSci 

+ 04-Feb-18: Kadena is hiring Haskell developers. http://bit.ly/2GMHBl1
  #Jobs #Haskell 

+ 04-Feb-18: Postdoctoral fellowship on "Nonstandard methods for Ramsey
  theory", Vienna (Austria). http://bit.ly/2GL1cSH #PostDoc #CompSci 

+ 02-Feb-18: 16 PhD positions on logical methods in computer science in
  Austria. http://bit.ly/2rZepng #PhD #Compsci 

+ 02-Feb-18: PhD student positions in theoretical computer science,
  Loughborough (England). http://bit.ly/2GGjzYO #PhD #Compsci  

+ 02-Feb-18: Postdoctoral fellowship in mathematical logic, Stockholm
  (Sweden). http://bit.ly/2s1lROQ #PosDoc #CompSci 

*** Enero de 2018

+ 28-Ene-18: Postdoc in Quantum Computing / Quantum Algorithms. University of
  Tartu, Estonia. http://bit.ly/2rIv5PT #PostDoc #CompSci 

+ 26-Ene-18: PhD student position: applications of finite semigroups in formal
  verification. Loughborough University (England). http://bit.ly/2rE7Qqd #PhD
  #CompSci 

+ 26-Ene-18: PhD studentship: String logics for query languages. Loughborough
  University (England). http://bit.ly/2GflMdn #PhD #CompSci 

+ 26-Ene-18: Postdoctoral Fellow in Mathematical Logic, Stockholm
  University. http://bit.ly/2GjEctq #PostDoc #Logic 

+ 26-Ene-18: Postdoctoral position and PhD student position in Algorithms,
  Potsdam (Germany). http://bit.ly/2Gj0ifP #PhD #PostDoc #CompSci 

+ 26-Ene-18: Postdoctoral position in logic, Gothenburg
  (Sweden). http://bit.ly/2FLrH9W #PostDoc #Logic  

+ 23-Ene-18: Two research assistant positions in satisfiability testing and
  computational modeling of human reasoning, Dresden
  (Germany). http://bit.ly/2rrFsr8 #PhD #CompSci 

+ 23-Ene-18: Three PhD student scholarships in computer science (including
  computational logic, formal languages), Tbilisi
  (Georgia). http://bit.ly/2G9IYdd #PhD #CompSci  

+ 23-Ene-18: Open positions in Tokyo: Formal methods and cyber-physical
  systems. http://bit.ly/2G7re2b #PostDoc #CompSci  

+ 18-Ene-18: 2 postdoc positions in distributed systems verification at
  University of Lugano and TU Darmstadt. http://bit.ly/2rjjXIZ #PostDoc
  #CompSci

+ 17-Ene-18: Various PhD student funding opportunities in theoretical computer
  Science, Swansea (Wales). http://bit.ly/2E65JN6 #PhD #CompSci 

+ 17-Ene-18: PhD position available, Imperial College London on the analysis
  and verification of concurrent and web programs. http://bit.ly/2EOoPb6 #PhD
  #CompSci  

+ 17-Ene-18: Research Associate Univ. de Cambridge: The project is entitled
  "How to (re)represent it?" and is led by Dr Mateja
  Jamnik. http://bit.ly/2FNrh2L #PhD #PostDoc #CompSci 

+ 17-Ene-18: Postdoc at Imperial College London on detecting and surviving
  exploitable compiler bugs. http://bit.ly/2EM6N9p #PostDoc #CompSci 

+ 17-Ene-18: Postdoc positions at the University of Pennsylvania to work on
  projects related to verification, software specification, and
  security. http://bit.ly/2FJBUUj #PostDoc #CompSci 

+ 17-Ene-18: Postdoctoral Fellowships at Trinity College Dublin supervised by
  staff members of the Foundations, Methods & Programming Languages
  Group. http://bit.ly/2EPs5Tn #PostDoc #CompSci  

+ 17-Ene-18: Two PhD positions on analysis and verification at the University
  of Chieti-Pescara in Italy. http://bit.ly/2ENntND #PhD #CompSci  

+ 17-Ene-18: Post-doc position at the Department of Computer Science and
  Engineering (University of Bologna, Italy) on: "Formal methods: description
  and analysis of distributed systems". http://bit.ly/2EOaUSf #PostDoc #CompSci   

+ 17-Ene-18: Post-doc "A formally verified symbolic interpreter for the CoLiS
  language". INRIA, Orsay http://bit.ly/2FMgypo #PostDoc #CompSci    

+ 17-Ene-18: Postdoctoral Researcher in Logic. University of
  Gothenburg. http://bit.ly/2FLrH9W #PostDoc #Logic

+ 04-Ene-18: PhD student position in SAT solving, Stockholm (Sweden). 
  http://bit.ly/2E8mYO1 #PhD #CompSci 

+ 04-Ene-18: Various PhD student funding opportunities in theoretical computer
  Science, Swansea (Wales). http://bit.ly/2E65JN6 #PhD #CompSci  

** 2017

*** Diciembre de 2017

+ 25-Dic-17: Postdoctoral positions in complexity theory, Stockholm
  (Sweden). http://bit.ly/2pyD29t #PostDoc #CompSci 

+ 25-Dic-17: Postdoctoral positions in algorithms and optimization with
  emphasis on theoretical aspects of machine learning at
  EPFL. http://bit.ly/2prKfrB #PostDoc #CompSci  

+ 21-Dic-17: PhD position in computer science focused on SAT Solving at KTH
  Royal Institute of Technology. http://bit.ly/2DloRqQ #PhD #CompSci

+ 21-Dic-17: Postdoc position in computer science focused on SAT solving at KTH
  Royal Institute of Technology. http://bit.ly/2p2IjFN #PhD #CompSci 

+ 21-Dic-17: Postdoc at CMU or a project in formal verification, dynamical
  systems, and constructive analysis. http://bit.ly/2p2koGB #PostDoc #CompSci 

+ 21-Dic-17: PhD student position in Cognitive Reasoning, Wernigerode
  (Germany). http://bit.ly/2p3WgU6 #PhD #CompSci 

+ 21-Dic-17: PhD student position in knowledge representation and reasoning
  techniques, Ulm (Germany). http://bit.ly/2p4GEQb #PhD #CompSci 

+ 12-Dic-17: Fully-funded PhD Studentship at Oxford in machine learning for
  verification. http://bit.ly/2nU7ObK #PhD #CompSci

+ 12-Dic-17: Postdoctoral research associate in proof-driven query planning (2
  posts). University of Oxford. http://bit.ly/2nSqvg4 #PostDoc #CompSci 

+ 12-Dic-17: PhD positions at the University of Pennsylvania in programming
  languages and formal methods. http://bit.ly/2nXniMr #PhD #CompSci 

+ 12-Dic-17: PhD position at Aalborg University: Compositional verification of
  real-time multi-core safety critical systems. http://bit.ly/2C5LE9D #PhD
  #CompSci 

+ 12-Dic-17: PhD student positions in computer science ("logic for agents"),
  Nottingham (England). http://bit.ly/2nRBExP #PhD #CompSci 

+ 10-Dic-17: Postdoctoral researcher in Logic. University of
  Gothenburg. http://bit.ly/2nLvAGN #PostDoc #Logic 

+ 09-Dic-17: 10 fully-funded PhD studentships. University of Nottingham -
  Computer Science. http://bit.ly/2nMls0I #PhD #CompSci

+ 09-Dic-17: The School of Computer Science in Nottingham is advertising 10
  fully-funded PhD studentships. Applicants in the area of the Functional
  Programming Lab are encouraged! http://bit.ly/2AnUGl7 #PhD #CompSci  

+ 04-Dic-17: PhD studentship in applications of logic and category theory to
  the semantics of  non-classical computational models, London
  (England). http://resources.illc.uva.nl/LogicList/newsitem.php?id=8659 #PhD
  #CompSci 

+ 01-Dic-17: One year fellowship in Padova on "Homotopy type theoretic aspects
  within he Minimalist  Foundation". http://bit.ly/2nKEeFt #PhD #Logic #CompSci 

*** Noviembre de 2017

+ 27-Nov-17: Multiple Ph.D. positions in the Software Factory 4.0 project at TU
  Darmstadt. http://bit.ly/2hYqeCx #PhD #CompSci 

+ 23-Nov-17: 2 studentships in Swansea Railway Verification Group on formal
  modelling, analysing and testing of real time systems. http://bit.ly/2nL1Yt9
  #PhD #CompSci 

+ 23-Nov-17: Job offer on formalizing complexity and termination techniques at
  the University of Innsbruck. http://bit.ly/2jsqslu #PhD #PostDoc #CompSci 

+ 22-Nov-17: PhD student positions in homotopy type theory, Pittsburgh PA
  (U.S.A.). http://resources.illc.uva.nl/LogicList/newsitem.php?id=8656 #PhD
  #CompSci 

+ 19-Nov-17: PhD positions at CMU for students interested in doing research in
  type theory, homotopy theory, (higher) category theory, and related
  areas. http://bit.ly/2hL7gzd #PhD #CompSci 

+ 17-Nov-17: PhD studentship on "The ethics of AI", Oxford
  (England). http://bit.ly/2hLGLtk #PhD #AI 

+ 16-Nov-17: Two postdoctoral positions on interpretable vector space models,
  Cardiff (Wales). http://bit.ly/2zZji2c #PostDoc #CompSci 

+ 14-Nov-17: Postdoc Positions at The University of Pennsylvania to work on
  projects related to verification, software specification, and
  security. http://bit.ly/2A1BKr6 #PostDoc #CompSci 

+ 13-Nov-17: Open Postdoc position on higher-order model checking, at the
  University of Tokyo, Japan. http://bit.ly/2zZcsJU #PostDoc #CompSci 
 
*** Octubre de 2017

+ 31-Oct-17: Data61 seeking proof engineers. http://bit.ly/2gYurJy #Job
  #CompSci

+ 31-Oct-17: Data61 seeking senior proof engineers. http://bit.ly/2gYurJy #Job
  #CompSci 

+ 31-Oct-17: #PostDoc in the project "Algorithms that count: exploring the
  limits of tractability" at Queen Mary, London. http://bit.ly/2gZ7Oo9 #CompSci

+ 31-Oct-17: PhD student position in Artificial Intelligence, Mannheim
  (Germany). http://bit.ly/2gXMu2H #PhD #CompSci 

+ 30-Oct-17: #Job opening at Symbiont in New York City: advanced type systems
  and/or formal verification techniques. http://bit.ly/2gWUL6R #CompSci 

+ 26-Oct-17: Research Fellowship to work on Homotopy Type
  Theory. http://bit.ly/2z8eFTZ #PostDoc #CompSci 

+ 25-Oct-17: Postdoctoral position in formal semantics and compiler
  verification http://eapls.org/items/2641 #PostDoc #CompSci 

+ 20-Oct-17: Postdoc in algorithmic economics, New York City NY
  (U.S.A.). http://bit.ly/2gYxHVk #PostDoc #CompSci 

+ 16-Oct-17: PhD student position in Artificial Intelligence (computational
  models of strategic behaviour), Warwick (England). http://bit.ly/2yurshX #PhD
  #CompSci 

+ 14-Oct-17: Postdoctoral position in natural language processing and knowledge
  representation. https://yhoo.it/2znEdJl #PostDoc #CompSci 

+ 11-Oct-17: Two PhD student positions in formal verification, Columbia MO
  (U.S.A.). http://bit.ly/2znQPR4 #PhD #CompSci 

+ 11-Oct-17: PhD student positions in theoretical computer science, Stockholm
  (Sweden). http://bit.ly/2zlHjO5 #PhD #CompSci  

+ 09-Oct-17: PostDoc position: "Specification and verification of quantum
  programming languages" at CEA and Uni. Paris Sud, France
  http://bit.ly/2y5V0TJ #PostDoc #CompSci

+ 04-Oct-17: PhD student position on formal verification of  security and
  privacy. Guildford (England). http://bit.ly/2xWfzPQ #PhD #CompSci 

+ 01-Oct-17: PhD student grants (in particular, mathematical logic and set
  theory), Hamburg (Germany). http://bit.ly/2xJ4gwO #PhD #Logic 

+ 01-Oct-17: #PostDoc and #PhD in applying formal verification to new
  biological computing devices. Israel. http://bit.ly/2xKyWhi #CompSci 
 
*** Septiembre de 2017

+ 28-Sep-17: PhD studentship in software engineering/programming languages in
  New York City. http://bit.ly/2xGwSXk #PhD #CompSci 

+ 28-Sep-17: Postdoctoral researcher position in the Security of Software Lab
  at the Pennsylvania State University. http://bit.ly/2xGwLem #PostDoc #CompSci 

+ 28-Sep-17: fortiss GmbH: Open-minded and pragmatic
  researcher. http://bit.ly/2xDFPhH #Job #CompSci  

+ 24-Sep-17: Two research associates in software testing, security and
  programming languages. Imperial College London. http://bit.ly/2fPv1Wm
  #PostDoc #CompSci

+ 22-Sep-17: Haskell job opportunity at RELEX Solutions in Helsinki,
  Finland. http://bit.ly/2xkvNob #Job #Haskell 

+ 21-Sep-17: Research associate in testing web browser security. Imperial
  College London, http://bit.ly/2xlaLWe #PostDoc #CompSci 

+ 19-Sep-17: Postdoctoral positions in automated reasoning at Stanford
  University. http://bit.ly/2fFI6RV #PostDoc #CompSci 

+ 18-Sep-17: PhD positions in Software Technology at Lund
  University. http://bit.ly/2ftDNc5 #PhD #CompSci 

+ 18-Sep-17: Postdoc positions in Software Technology at Lund
  University. http://bit.ly/2fttiWk #PostDoc #CompSci

+ 14-Sep-17: PhD studentships in computing at Imperial College
  London. http://bit.ly/2y8hr7S #PhD #CompSci 

+ 14-Sep-17: Postdoctoral position in SAT solving, Stockholm
  (Sweden). http://bit.ly/2y8h0dK #PostDoc #CompSci

+ 12-Sep-17: PhD research fellow position in Proof Engineering Technologies in
  Probabilistic Programming and Software Verification. http://bit.ly/2xhLhJh
  #PhD #CompSci 

+ 12-Sep-17: PhD positions in "Verification of Quantum Cryptography"
  http://bit.ly/2eSaAH7 #PhD #CompSci 

+ 12-Sep-17: Researcher positions (postdoc) in "Verification of Quantum
  Cryptography". http://bit.ly/2eRzd71 #PostDoc #CompSci 

+ 10-Sep-17: PhD student positions in mathematics, Helsinki
  (Finland). http://bit.ly/2eRY4aO #PhD #Logic 

+ 09-Sep-17: Functional Jobs: Backend Ruby and Haskell engineer at Health
  eFilings (Full-time) http://bit.ly/2xV9zq4 #Jobs #Haskell

+ 08-Sep-17: A PhD position in the area of "Formal methods for requirements
  validation of resilient systems" in Trento. http://bit.ly/2eSrNQG #PhD
  #CompSci 

+ 07-Sep-17: Concurrency/verification positions at Politecnico di
  Milano. http://bit.ly/2wIGqzQ #PostDoc #CompSci

+ 06-Sep-17: Call for Inria postdoc applications in formal methods for
  security. http://bit.ly/2wJsQwe #PostDoc #CompSci

+ 06-Sep-17: Open positions in Tokyo: Formal methods and cyber-physical
  systems. http://bit.ly/2wJM8BM #PhD #PostDoc #CompSci

+ 01-Sep-17: Position of Junior Quant Researcher at
  ARFIMA. http://bit.ly/2wXoBhW #PostDoc #Math #CompSci

*** Agosto de 2017

+ 31-Ago-17: Postdoctoral research associate in verifiable autonomous robotics
  within hazardous environments. Univ. Liverpool http://bit.ly/2x7sBf2 #PostDoc
  #CompSci 

+ 28-Ago-17: Two PhD Positions in social network analysis.http://bit.ly/2wZdc03
  #PhD #CompSci   

+ 26-Ago-17: Six full professorships in computing (including algorithms &
  complexity), Leeds (England). http://bit.ly/2vzHJ1d #Jobs #CompSci 

+ 26-Ago-17: PhD student position in software testing and verification at
  Mälardalen University http://bit.ly/2wGKT7k #PhD #CompSci 

+ 17-Ago-17: Research position in formal methods for intelligent
  cars. http://bit.ly/2vXKtYO #PostDoc #CompSci 

+ 14-Ago-17: Academic position at University of Glasgow, Scotland
  (UK). http://bit.ly/2vX50wu #PostDoc #CompSci 

+ 09-Ago-17: PhD student position in correct parallel algorithms, Leiden (The
  Netherlands). http://bit.ly/2vRHzpB #PhD #CompSci 

+ 04-Ago-17: PhD research fellow position in Proof Engineering Technologies in
  Probabilistic Programming and Software Verification http://bit.ly/2ujNDD7
  #PhD #CompSci 

+ 04-Ago-17: Postdoc in program semantics at Appalachian State
  University. http://bit.ly/2vIwyWN #PostDoc #CompSci 

+ 04-Ago-17: Research assistant / associate in disciplined approximate
  arithmetic. Imperial College London. http://bit.ly/2vIb0cP #PhD #PostDoc
  #CompSci 

*** Julio de 2017

+ 30-Jul-17: Postdoctoral position on effects and/or type theory at Inria in
  Nantes. http://bit.ly/2ukpXy4 #PostDoc #CompSci 

+ 26-Ju-17: #PostDoc in the project "Semantics, formal reasoning, and tool
  support for quantum programming”. Tulane Univ. http://bit.ly/2tLR7Sn #CompSci 

+ 27-Jul-17: Postdoc position in program verification at Carnegie Mellon
  University, Silicon Valley http://bit.ly/2ujNOhv #PostDoc #CompSci 

+ 25-Jul-17: #Job: Software engineer, static analysis at
  Facebook. https://www.facebook.com/careers/jobs/a0I1200000LT8aA #CompSci

+ 24-Jul-17: #PhD / #PostDoc position to work in the Tyrex group at
  INRIA/UGA/CNRS in Grenoble, France. http://bit.ly/2tM44Md #CompSci  

+ 23-Jul-17: #PhD studentship in verification of security and privacy in modern
  threat landscapes. Univ. of Surrey http://bit.ly/2uryLmN #CompSci 

+ 21-Jul-17: #PostDoc and #PhD positions in security & concurrency with formal
  methods. TU Darmstadt. http://bit.ly/2vMzRc7 #CompSci 

+ 20-Jul-17: #PostDoc research position in theorem proving at University of
  Manchester, UK. http://bit.ly/2vMNQyG #CompSci 

+ 19-Jul-17: Open PhD positions with a particular focus on Formal
  Verification. University of Lübeck https://goo.gl/j9Co2y #PhD #CompSci 

+ 17-Jul-17: #PostDoc researcher and (senior) research associate/scientist
  positions on automatic software analysis, transformation, and security
  hardening at Penn State University. http://bit.ly/2vMOrAJ #CompSci 

+ 15-Jul-17: Postdoctoral fellowship in computational models of reasoning,
  Washington DC (U.S.A.). http://bit.ly/2tszQc4 #PostDoc #CompSci

+ 14-Jul-17: #PhD/#PostDoc position at the programming languages
  group. University of Freiburg. http://bit.ly/2vMx2Ii #CompSci 

+ 11-Jul-17: Postdoc (PhD) position @ MPI-SWS in software verification and
  approximate computing. http://bit.ly/2tsLFyR #PhD #PostDoc #CompSci 

+ 10-Jul-17: #Postdoctoral fellowship at the interface between algebraic
  topology and neuronal systems. BCAM. http://bit.ly/2v2QUqh #Math #CompSci

+ 07-Jul-17: Funded PhD studentship: Integrating automated provers in proof assistants. http://bit.ly/2v2XOvo #PhD #CompSci

+ 04-Jul-17: Funded PhD positions at Edinburgh verifying embedded ARM
  security. http://bit.ly/2u4mXJg #PhD #CompSci 

*** Junio de 2017

+ 30-Jun-17: #PostDoc position within the project "Translating and discovering
  calculi for modal and related logics" http://bit.ly/2u4qfMg #Logic #CompSci 

+ 29-Jun-17: Programa de becas de movilidad académica entre instituciones
  asociadas a la AUIP (Asociación Universitaria Iberoamericana de
  Postgrado) 2017. http://www.auip.org/es/becasauip

+ 29-Jun-17: Programa de becas de movilidad entre universidades andaluzas e
  iberoamericanas 2017. http://www.auip.org/es/becasauip

+ 27-Jun-17: Postdoctoral position on first-order theory of rewriting,
  Innsbruck (Austria). http://bit.ly/2u3XgZ5 #PostDoc #CompSci 

+ 26-Jun-17: Research associate in approximate computing with application to
  machine learning. http://bit.ly/2v2Np39 #PhD_CompSci 

+ 22-Jun-17: PostDoc position within the project "Communication contracts for
  distributed systems development". Univ. of Lisbon. http://bit.ly/2v2HTxo
  #PosDoc_CompSci 

+ 22-Jun-17: EPSRC Funded PhD Studentship: Testing from verified test-models
  for ERTMS level 2 at Swansea, UK http://bit.ly/2rG4sqv #PhD #CompSci 

+ 22-Jun-17: A 3 year PhD with Grenoble University on service composition for
  safety and security. http://bit.ly/2rFI6W3 #PhD #CompSci

+ 20-Jun-17: #Postdoc and #PhD positions in the ERC grant "A rigorous approach
  to consistency in cloud databases" at IMDEA, Madrid http://bit.ly/2sZc4Z3
  #CompSci 

+ 20-Jun-17: Twelve #PhD student positions in "Uncertainty & randomness in
  algorithms, verification & logic", Aachen (Germany) http://bit.ly/2rFEjbn
  #CompSci  

+ 19-Jun-17: Three #PhD positions in Security and Privacy at the University of
  Luxembourg. http://bit.ly/2sYD22O #CompSci 

+ 13-Jun-17: #PhD student position in proof theory, Gothenburg
  (Sweden). http://bit.ly/2sYX90P #Logic  

+ 10-Jun-17: #PhD student position and #postdoctoral position in program
  logics, Erlangen (Germany). http://bit.ly/2sYLfnv #CompSci 

+ 08-Jun-17: #PhD and #Postdoc position in monad-based programming and
  verification at FAU. http://bit.ly/2sYRjNb #CompSci 

+ 06-Jun-17: #PhD on lambda-calculus, in Paris. http://bit.ly/2sYDHkY #Logic
  #CompSci 

+ 03-Jun-17: 2 #postdoct positions in a project concerned with the
  formalisation of mathematics within Isabelle/HOL. Cambridge (England)
  http://bit.ly/2rFQuF1 

+ 03-Jun-17: Three #postdoctoral research associates on interactive theorem
  proving, Cambridge (England) http://bit.ly/2sZ1p0g #CompSci  

+ 01-Jun-17: #Postdoc position in the project "FORTissimo: Automating the
  first-order theory of rewriting" at Innsbruck. http://bit.ly/2rFKCLQ #CompSci 

*** Mayo de 2017

+ 30-May-17: #Postdoct position on graph data mining and anomaly
  detection. http://bit.ly/2rFyM4A #CompSci 

+ 23-May-17: #Postdoct position in program analysis at the University of
  Colorado Boulder. http://bit.ly/2sYVkRz #CompSci 

+ 20-May-17: #Postdoct researcher and (senior) research associate/scientist
  positions at Penn State University. http://bit.ly/2sZ0Zab #CompSci  

+ 20-May-17: #PostDoc position on the topic of certified cost analysis
  of functional programs at Wesleyan University. http://bit.ly/2q3vnM1 #CompSci  

+ 20-May-17: PostDoc in the project NSF "Relaxing soundness" at DePaul
  University. http://bit.ly/2q3lIoF #PostDoc #CompSci 

+ 20-May-17: Research position in Program Verification and
  Security. http://bit.ly/2q30Qhg #PostDoc #CompSci 

+ 14-May-17: 22 PhD student positions in autonomous systems and
  software. http://bit.ly/2pKfiuE #PhD #CompSci 

+ 14-May-17: Assistant Professor in Mathematics. KU Leuven
  University. http://bit.ly/2pKeRk0 #Job #Math 

+ 14-May-17: Postdoctoral research fellowship (2y) in dynamical
  multi-agent systems, Stockholm (Sweden). http://bit.ly/2pKIdi7 #PostDoc
  #CompSci 

+ 14-May-17: Two PhD student positions in computational linguistics,
  Utrecht (The Netherlands) http://bit.ly/2pKRPt2 #PhD #CompSci 

+ 14-May-17: PhD student and postdoctoral positions in Information Security,
  Stuttgart (Germany). http://bit.ly/2pKRwyi #PhD #PostDoc #CompSci 

+ 14-May-17: PhD student position on agent-based modeling of drones in
  France. http://bit.ly/2pKxPH0 #PhD #CompSci 

+ 14-May-17: PhD position in Groningen on concurrency theory / semantics /
  process calculi. http://bit.ly/2pKRbvC #PhD #CompSci 

+ 14-May-17: Researcher positions (postdoc) in "Verification of quantum
  cryptography" at the University of Tartu, Estonia. http://bit.ly/2pKJaHe
  #PostDoc #CompSci  

+ 14-May-17: Open PostDoc and Ph.D. positions in concurrency and software
  security at TU Darmstadt, Germany. http://bit.ly/2r5Pmxr #PhD #PosDoc
  #CompSci 

+ 14-May-17: Haskell development jobs with Well-Typed. http://bit.ly/2reTbh5
  #Haskell #Jobs 

+ 14-May-17: Haskell startup jobs. https://angel.co/haskell/jobs #Haskell

+ 12-May-17: Galois is hiring. ~ Daniel Wagner http://bit.ly/2q7MXz7 #Job
  #CompSci 

+ 12-May-17: PhD student position on functional heterogenous systems, in the
  functional programming group at Chalmers http://bit.ly/2q7JTmy #PhD #CompSci 

+ 11-May-17: Researcher positions in HoTT at Carnegie Mellon
  University. http://bit.ly/2q6pYEB #PostDoc #CompSci 

+ 11-May-17: Postdoc position at MPI-SWS, Kaiserslautern,
  Germany. http://bit.ly/2q6ozxN #PostDoc #CompSci 

+ 05-May-17: Assistant Professorship in Theoretical Foundations of Computer
  Science, Umea (Sweden). http://bit.ly/2qKK3zu #Job #CompSci 

+ 05-May-17: PostDoc in the project "Multivariate algorithms: new domains and
  paradigms". Univ. of Bergen, Norway http://bit.ly/2qKS4EK #PostDoc #CompSci

+ 04-May-17: Software Engineering/Research Intern - Galois,
  Inc. http://bit.ly/2pD1IeZ #Job #CompSci #Haskell   

+ 04-May-17: #PhD and #PostDoc positions in the project "Strong modular proof
  assistance: reasoning across theories". Innsbruck. http://bit.ly/2pCSz61
  #CompSci  

+ 04-May-17: PhD position on security and privacy of location-based services at
  Chalmers, Sweden. http://bit.ly/2pCNlav #PhD #CompSci  

+ 04-May-17: Kernkonzept seeks outstanding formal-methods experts to join their
  team in Dresden, Germany. http://bit.ly/2pCHQbN #Job #CompSci 

+ 04-May-17: 1-2 PhD positions on combining formal methods and machine learning
  (U. of Oslo). http://bit.ly/2pCVThz #PhD #CompSci 

+ 04-May-17: Research (postdoc or graduate) position in program verification
  and security. http://bit.ly/2qD2rdJ #PhD #PostDoc #CompSci 

+ 03-May.17: Haskell engineering role working on data security.
  http://hubs.ly/H07llVW0 #Job #Haskell

+ 03-May-17: Research (postdoc or graduate) position in program verification
  and security. http://bit.ly/2qD2rdJ #PostDoc #CompSci 

+ 03-May-17: PhD position in the field of programming techniques and
  programming languages. U Tuebingen, Germany. http://bit.ly/2qCLBM7 #PhD
  #CompSci 

*** Abril de 2017

+ 28-Abr-18: Summer contracting opportunity for CodeWorld. #Job #Haskell
  https://mail.haskell.org/pipermail/haskell-cafe/2017-April/126903.html 

+ 23-Abr-17: #PhD student position in software engineering, highly configurable
  systems, formal methods at Chalmers. Univ. of Gothenburg, Sweden
  http://bit.ly/2ppz3uL  

+ 23-Abr-17: Open positions in Tokyo: Metamathematics for systems design
  project. http://bit.ly/2ppBXj0 #Jobs #PostDoc #PhD #CompSci 

+ 23-Abr-17: OCaml jobs at genomics company in New York City.
  http://bit.ly/2ppBmy0  #Job #FunctionalProgramming 

+ 23-Abr-17: Postdoctoral position in automata theory, Lyon
  (France). http://bit.ly/2q3lhud #PostDoc #CompSci 

+ 23-Abr-17: PhD position: Order structures in bi-partite data, (at University
  of Kassel) http://bit.ly/2q3oR7B #PhD #CompSci   

+ 15-Abr-17: PhD position in Eindhoven on formal verification and GPU computing
  http://bit.ly/2phVXE2 #PhD #CompSci 

+ 12-Abr-17: #PostDoc position at Wesleyan University on the topic of certified
  cost analysis of functional programs. http://bit.ly/2o4LhDU #CompSci 

+ 11-Abr-17: #PostDoc position at Queen Mary with a strong background in
  programming languages and verification. http://bit.ly/2omFi0w #CompSci 

+ 10-Abr-17: #PostDoc position: source-code level program
  verification. Singapore Univ. of Technology and Design http://bit.ly/2oXrSGC
  #CompSci  

+ 10-Abr-17: 2 #PhD positions and 1 #PostDoc position in Twente (Netherlands):
  Maximal Reliability of Concurrent and Distributed
  Software. http://bit.ly/2oXyQLU #CompSci 

+ 10-Abr-17: #PhD positions at the University of Leicester: Type Theory, Logic
  in Computer Science, Verification, and Category Theory. http://bit.ly/2oXH078
  #CompSci  

+ 10-Abr-17: Associate Professor (TF) of Theoretical Computer Science in
  Oxford. http://bit.ly/2oXsRa1 #Job #CompSci 

+ 10-Abr-17: #PostDoc position in machine learning for formal methods at Rice
  University. http://bit.ly/2oXwT29 #CompSci 

+ 10-Abr-17: #PostDoc research fellowship in algorithmic game theory, Warwick
  (England). http://bit.ly/2oXN4fD #CompSci 

+ 02-Abr-17: Associate Professorship in Logic (potentially tenure-track),
  Hangzhou (China). http://bit.ly/2mXS6vD #Job #Logic 

+ 02-Abr-17: Postdoctoral position (3y+3y) in mathematics (algebra or analysis
  or logic), Gent (Belgium). http://bit.ly/2mXUUss #PostDoc #Logic 

+ 02-Abr-17: PhD student positions in multi-agent systems, London
  (England). http://bit.ly/2mY087I #PhD #CompSci 

*** Marzo de 2017

+ 27-Mar-17: Two PhD positions on CakeML and HOL at Chalmers,
  Sweden. http://bit.ly/2n8PyGb #PhD #CompSci 

+ 24-Mar-17: Positions in Swansea with opportunities in types, semantics,
  programming languages, verification, logic. http://bit.ly/2oedIjj #Job
  #CompSci 

+ 23-Mar-17: Postdoctoral research fellowship on category theory, North Ride
  NSW (Australia). http://bit.ly/2o9pj2W #PostDoc #Logic #CompSci 

+ 23-Mar-17: PhD student or postdoc position in description logic, Bremen
  (Germany). http://bit.ly/2o98mpl #PhD #PostDoc #CompSci 

+ 23-Mar-17: PhD student position in quantitative logics and automata, Dresden
  (Germany). http://bit.ly/2o91kB1 #PhD #CompSci 

+ 23-Mar-17: PhD student position in SAT solving, Stockholm
  (Sweden). http://bit.ly/2o955ql #PhD #Logic #CompSci 

+ 23-Mar-17: Postdoc position in proof theory in Paris. http://bit.ly/2o96VaC
  #PostDoc #Logic 

+ 23-Mar-17: Postdoc in semantics and tools for functional quantum programming
  languages. http://bit.ly/2o932CF #PostDoc #CompSci 

+ 23-Mar-17: Funded PhD studentship on formal verification for wireless sensor
  networks. University of Liverpool, UK http://bit.ly/2o92cWm #PhD #CompSci 

+ 23-Mar-17: #PostDoc on automated verification of properties of concurrent,
  distributed and parallel specifications. Copenhagen http://bit.ly/2nrQ5GZ
  #CompSci

+ 05-Mar-17: PhD student position in logic for decision making in security,
  Bath (England). http://bit.ly/2mpFxaO #PhD #CompSci 

+ 04-Mar-17: PhD student positions in artificial intelligence, Manchester
  (England). http://bit.ly/2m6BmzS #PhD #CompSci #AI 

+ 04-Mar-17: PhD student position in homotopy type theory, Amsterdam (The
  Netherlands). http://bit.ly/2m6JkJp #PhD #Logic #CompSci 

+ 04-Mar-17: PhD student position in "Les Corses avaient-ils raison?", Paris
  (France). http://bit.ly/2m71TNJ #PhD #CompSci 

+ 04.Mar-17: Postdoctoral researcher in Mathematical Logic and AI, Amsterdam
  (The Netherlands). http://bit.ly/2m6tK0C #PosDoc #CompSci 

+ 04-Mar-17: Assistant/Associate Professorship (tenure track) in computational
  linguistics, Trento (Italy). http://bit.ly/2mXwYky #Job #CompSci 

+ 02-Mar-17: Fully-funded PhD in Formal Verification at
  Oxford. http://bit.ly/2lWwWfc #PhD #CompSci 

+ 01-Mar-17: Convocatoria de becas Andalucia Open Future para alumnos de
  estudios de posgrado de la Universidad de Sevilla. http://bit.ly/2mf5LwR  

+ 01-Mar-17: Santander Universidades convoca 31 Becas Iberoamérica para
  estudiantes de la US. http://bit.ly/2mf3dPw  

+ O1-Mar-17: Postdoc at Inria/Irisa on translation validation from Liquid
  Haskell http://bit.ly/2meLsjb #PosDoc #CompSci #Haskell 

+ 01-Mar-17: Postdoc position in Computer Science focused on SAT Solving at KTH
  Royal Institute of Technology. http://bit.ly/2meUJI9 #PostDoc #CompSci

+ 01-Mar-17: PhD positions computational complexity at KTH Royal Institute of
  Technology. http://bit.ly/2meDHcY #PhD #CompSci

+ 01-Mar-17: Ten PhD positions in "Computer Science" at the Gran Sasso Science
  Institute http://bit.ly/2meMuvA #PhD #CompSci

*** Febrero de 2017

+ 11-Feb-17: Postdoc at Sapienza University of Rome in the areas of algorithms,
  data mining and machine learning. http://bit.ly/2kfGf5I #CompSci  

+ 11-Feb-17: 2 postdocs in algorithmic game theory and dynamical systems. SUTD,
  Singapore http://bit.ly/2l3A5cX #PostDoc #CompSci  

+ 07-Feb-17: #PhD student position in logic & security, London (England)
  http://bit.ly/2lgj0NF #CompSci  

+ 07-Feb-17: Postdoc in sublinear/randomized algorithms at University of
  Warwick. http://bit.ly/2lm6eKv #PostDoc #CompSci 

+ 04-Feb-17: #PostDoc position at the University of Kent: "Verifying concurrent
  algorithms on weak memory models" project. http://bit.ly/2l7kpTo #CompSci 

+ 04-Feb-17: Postdoc position at IT University of Copenhagen: "Type theories
  for reactive programming" project. http://bit.ly/2l3rbgs #PostDoc #CompSci 

+ 03-Feb-17: Open PhD position to work on the SAPIC/Tamarin security protocol
  verification tool chain. Inria Nancy - Grand Est http://bit.ly/2l24iqr #PhD
  #CompSci

+ 03-Feb-17: Functional programming for runtime verification of flight-critical
  systems | NASA. http://bit.ly/2jEsDW4 #Job #Haskell

+ 02-Feb-17: Haskell developer roles at Standard Chartered.
  http://bit.ly/2kVqq5x #Job #CompSci 

+ 01-Feb-17: #PostDoc opening on communication contracts for distributed
  systems development. University of Lisbon. http://bit.ly/2jtU4ls #CompSci 

+ 01-Feb-17: Postdoctoral position on statistical program analysis and
  synthesis at Rice University http://bit.ly/2kPJ2nQ #PostDoc #CompSci  

+ 01-Feb-17: Research positions at Galois. http://bit.ly/2kPHKcl #Jobs #CompSci

*** Enero de 2017

+ 29-Ene-17: PhD position: Formal methods in control (Munich,
  Germany). http://bit.ly/2kfn9jK #PhD #CompSci 

+ 29-Ene-17: A Postdoc position in Imperial College London. 
  http://bit.ly/2kAuTdS #PostDoc #CompSci

+ 29-Ene-17: Multiple research positions, "Type and proof structures for
  concurrent software verification" project, Madrid, Spain
  http://bit.ly/2kAnxqN #PhD #PostDoc #CompSci 

+ 27-Ene-17: Postdoc positions available for ERC "RustBelt" project on
  foundations of Rust. http://bit.ly/2k9NnVk #PostDoc #CompSci 

+ 25-Ene-17: PhD position in Systematic testing of concurrent programs at
  Uppsala University, Sweden. http://bit.ly/2ktUc0p #PhD #CompSci

+ 20-Ene-17: Postdoc opening on weak memory concurrency at the Max Planck
  Institute for Software Systems (MPI-SWS). http://bit.ly/2iIpFzH #PostDoc
  #CompSci 

+ 18-Ene-17: #Job: Associate Professor/Professor of Automated Verification,
  with Tutorial Fellowship at St. John's College, Univ. of
  Oxford. http://bit.ly/2iBSsWm #CompSci 

+ 14-Ene-17: 5 year postdoc position in computational logic. University of
  Innsbruck. http://bit.ly/2jiJn3K #PostDoc #CompSci 

+ 14-Ene-17: Postdoc in SDN verification and security at
  Edinburgh. http://bit.ly/2jiC8Jc #PostDoc #CompSci 

+ 14-Ene-17: Postdoc position in applied semantics for production
  architectures. http://bit.ly/2jiOyka #PostDoc #CompSci 

+ 11-Ene-17: PhD position at Durham University for work on Cadabra and related
  topics in symbolic computer algebra. http://bit.ly/2jjHphj #PhD #CompSci  

+ 09-Ene-17: Postdoc in algorithms at The Open University of
  Israel. http://bit.ly/2iWiL8C #PostDoc #CompSci 

+ 07-Ene-17: Postdoctoral position in artificial intelligence, Cardiff
  (Wales). http://bit.ly/2iMjr0s #PostDoc #CompSci 

+ 04-Ene-17: Postdoc in theoretical computer science at Duke
  University. http://bit.ly/2iyBEhW #PostDoc #CompSci 

+ 03-Ene-17: PhD student position in logic, Amsterdam (The
  Netherlands). http://bit.ly/2hK4aJb #PhD #Logic #CompSci

** 2016 

*** Diciembre de 2016

+ 29-Dic-16: Funded PhD Positions in Runtime Verification and Model Checking at
  Iowa State University. http://bit.ly/2hrmmqS #PhD #CompSci 

+ 24-Dic-16: 10+ Open Positions in Tokyo: Formal Methods and Cyber-Physical
  Systems. http://bit.ly/2hbFNUn #PhD #PostDoc #CompSci 

+ 24-Dic-16: 2 PhD positions @University of Twente: Fewer train delays via big
  data, fault trees, model checking. http://bit.ly/2inzKkC #PhD #CompSci

+ 24-Dic-16: W3 Professorship in Machine Learning, Konstanz
  (Germany). http://bit.ly/2inxsCb #Job #CompSci 

+ 22-Dic-16: Software Engineering/Research Intern - Galois,
  Inc. http://bit.ly/2idFVYq #Job #CompSci #Haskell  

+ 21-Dic-16: PhD study on formal verification for wireless sensor
  networks. University of Liverpool. http://bit.ly/2ibX7Oc #PhD #CompSci 

+ 20-Dic-16: Full Stack Clojure Engineer at Wade & Wendy (Full-time)
  http://bit.ly/2gYqBKv #Job #Clojure 

+ 20-Dic-16: Postdoc position in provably secure systems, KTH Royal Institute
  of Technology, Stockholm, Sweden. http://bit.ly/2gYiA88 #PostDoc #CompSci 

+ 20-Dic-16: Se busca un investigador para el proyecto "Unidad mixta de
  investigación Repsol-ITMATI". http://bit.ly/2gYBOKN #Trabajo #Matemáticas
  #Computación 

+ 20-Dic-16: Faculty positions in programming languages, and formal
  verification at Stevens (NYC area) http://bit.ly/2i3Wx4P #Job #CompSci

+ 20-Dic-16: Assistant and associate professor openings at Aarhus University,
  Denmark. http://bit.ly/2gWiDkR #Job #CompSci 

+ 17-Dic-16: Postdoc position in applied semantics for production
  architectures. Univ. of Cambridge http://bit.ly/2hWiOle #PosDoc #CompSci

+ 17-Dic-16: Two postdoc positions in quantum programming languages, at
  Dalhousie University. http://bit.ly/2gPgSGl #PosDoc #CompSci

+ 17-Dic-16: Post-doc positions at ENS Lyon, in Computer Science and
  Mathematics. http://bit.ly/2gPgFCU #PostDoc #CompSci

+ 17-Dic-16: Postdoc in computer science focused on SAT solving, KTH Royal
  Institute of Technology, Stockholm, Sweden. http://bit.ly/2gPnrZ6 #PostDoc
  #CompSci 

+ 17-Dic-16: PhD student position in logic and verification for AI, Utrecht
  (The Netherlands). http://bit.ly/2gPo0Cj #PdD #CompSci 

+ 17-Dic-16: #PostDoc positions in theoretical computer science, KTH Royal
  Institute of Technology, Stockholm, Sweden. http://bit.ly/2gPlWu2 #CompSci 

+ 17-Dic-16: #PhD positions in theoretical computer science, KTH Royal
  Institute of Technology, Stockholm, Sweden. http://bit.ly/2gPpyMw #CompSci

+ 17-Dic-16: PhD student position in dependence logic, Auckland (New
  Zealand). http://bit.ly/2hWoefT #PhD #CompSci #Logic

+ 17-Dic-16: #PhD and #PostDoc vacancy on normative and value-based reasoning
  for socially adaptive software, Delft (The Netherlands) http://bit.ly/2gPlCeW
  #CompSci

+ 11-Dic-16: PhD positions on the AI4REASON project in
  Prague. http://bit.ly/2hja7ho #PhD #CompSci 

+ 10-Dic-16: Three open faculty positions at the Max Planck Institute for
  Software Systems. http://bit.ly/2gvDGOl #Job #CompSci 

+ 10-Dic-16: Associate/Assistant Professor in Programming Languages at the
  Technical University of Denmark. http://bit.ly/2heGH3G #Job #CompSci 

+ 10-Dic-16: Postdoc positions - Center for Advanced Software Analysis, Aarhus
  University http://bit.ly/2heEIfS #PostDoc #CompSci

+ 10-Dic-16: Postdoc position in the area of formal verification at Middlesex
  University London, UK. http://bit.ly/2gvB570 #PostDoc #CompSci

+ 10-Dic-16: PhD Candidate ‘Parameterized complexity of approximate Bayesian
  inferences’ Nijmegen (The Netherlands) http://bit.ly/2heMk1R #PhD #CompSci
  #Logic

+ 10-Dic-16: The Chair of Programming Methodology at ETH Zurich is looking for
  excellent candidates for newly-opened PhD positions. http://bit.ly/2heHAJE
  #PhD #CompSci 

+ 10-Dic-16: Lecturer/Senior Lecturer openings in Artificial Intelligence and
  Machine Learning at Imperial College London. http://bit.ly/2gvAPoC #Job
  #CompSci 

+ 10-Dic-16: The Northwestern Theory group seeks applications for 1-2
  postdoctoral positions starting in September 2017. http://bit.ly/2gvRpol
  #PostDoc #CompSci 

+ 04-Dic-16: Open Postdoc Position on Higher-Order Model Checking. University
  of Tokyo, Japan. http://bit.ly/2gponEe #PostDoc #CompSci

*** Noviembre de 2016

+ 28-Nov-16: #PhD opportunities in programming languages, testing and
  verification for heterogeneous many-core systems. http://bit.ly/2ga05AK
  #CompSci  

+ 25-Nov-16: Postdoctoral Associate in the area of theoretical machine
  learning. Rutgers University http://bit.ly/2fMY3n8 #PostDoc #CompSci 

+ 25-Nov-16: DIMACS Postdoc Positions http://bit.ly/2fMYJsO #PostDocs #CompSci

+ 25-Nov-16: PostDocs, internships in Cryptography. Tel Aviv University
  http://bit.ly/2fN1pqg #PosDoc #CompSci

+ 25-Nov-16: PhD opportunities at the Univ. of Minnesota http://bit.ly/2g03xy5
  #PhD #CompSci 

+ 25-Nov-16: PhD positions in Computer Science, Liverpool
  (England). http://bit.ly/2g04q9F #PhD #CompSci

+ 25-Nov-16: PhD student position in specification and verification of
  data-aware systems, Evry (France). http://bit.ly/2fZVcKF #PhD #CompSci

+ 25-Nov-16: Postdoctoral position in logic, Barcelona (Spain). 
  http://bit.ly/2fMNsJ9 #PostDoc #Logic

+ 22-Nov-16: PhD studentships in programming languages at LFCS, University of
  Edinburgh. http://bit.ly/2fMO7wL #PhD #CompSci 

+ 18-Nov-16: Postdoc position in distributed systems/verification/Coq at
  University College London (UCL). http://bit.ly/2g44fJ5 #PosDoc #CompSci 

+ 11-Nov-16: Assistant / Associate Professorship in Algorithmics, Delft (The
  Netherlands). http://bit.ly/2fi3opj #Job #CompSci 

+ 10-Nov-16: Postdoc at Simons Algorithms and Geometry Collaboration
  http://bit.ly/2fEwJsy #PostDoc #CompSci 

+ 08-Nov-16: PhD Student positions in Cyber-physical Systems/Artificial
  Intelligence/Systems Biology at ANU http://bit.ly/2fdxs5c #PhD #CompSci 

+ 05-Nov-16: Faculty positions at the University of Cambridge, in Programming
  Languages, Systems, and Cyber-Physical Systems. http://bit.ly/2f3MpqJ

+ 05-Nov-16: Postdoc position in verification of infinite-state
  systems. University of Iowa. http://bit.ly/2f3EB8o #PostDoc #CompSci

+ 05-Nov-16: Postdoctoral Researcher Formal Verification of Safety Critical
  Software. Radboud University http://bit.ly/2f3InyE #PostDoc #CompSci 

*** Octubre de 2016

+ 30-Oct-16: Research data manager position. The Heart Healthy Hoods
  project. Madrid http://bit.ly/2f3Op0u #Job #DataScience 

+ 29-Oct-16: Functional Jobs: Software Engineer (Haskell/Clojure) at Capital
  Match (Full-time) http://bit.ly/2fjhU1E #Job #Haskell

+ 29-Oct-16: Competitively paid postdoc position in
  Denmark. http://bit.ly/2eTdvks #PostDocs #CompSci 

+ 29-Oct-16: Faculty Position in Intelligent Systems & Autonomy. Iowa State
  University http://bit.ly/2eTcHwc #Jobs #CompSci 

+ 29-Oct-16: PhD studentship in mathematical models of access control policies,
  London (England). http://bit.ly/2eTczg4 #PhD #CompSci 

+ 29-Oct-16: Temporary Assistant Professorship (4y) in formal modelling of
  language and cognition, Amsterdam. http://bit.ly/2ePqmBu #Job #CompSci  

+ 23-Oct-16: PhD positions available at Stanford
  University. http://bit.ly/2dX4fIt #PhD #CompSci #Automated_reasoning

+ 17-Oct-16 Positions at Iowa State University: faculty and PhD
  students. http://bit.ly/2dKLEzm #PhD #CompSci 

+ 17-Oct-16 PhD student position in language-based security using functional
  languages at Chalmers http://bit.ly/2dKJBLu #PhD #CompSci  

+ 17-Oct-16 Postdoctoral position in verification of linear dynamical systems,
  Oxford (England) http://bit.ly/2dKMH1W #PostDoc #CompSci

+ 12-Oct-16 2 Post-Docs on power of algorithms in discrete optimisation at
  University of Oxford http://bit.ly/2dWD83D #Job #CompSci 

+ 12-Oct-16: Galois has positions open for Software Engineers/Researchers
  http://bit.ly/2dWjFjy #Job #CompSci 

+ 12-Oct-16: Galois has positions open for a Machine Learning Software
  Engineer. http://bit.ly/2dWlXPx #Job #CompSci

+ 12-Oct-16: Galois has positions open for a Researcher/Principal Investigator
  in Portland, OR and Arlington, VA. http://bit.ly/2dWiZe0 #Job #CompSci 

+ 10-Oct-16: 2 #PostDocs positions: Practical just-right consistency and
  planet-scale storage. http://bit.ly/2dRESea #CompSci

+ 10-Oct-16: Postdoc/Research fellow position in Formal Methods and System
  Security, ShanghaiTech University, China http://bit.ly/2dq5teX #PostDoc #CompSci

+ 01-Oct-16: Full-time Haskell jobs in London, at Barclays. http://bit.ly/2d32o4f
  #Job #Haskell

*** Septiembre de 2016

+ 27-Sep-16: Open Ph.D. position in formal methods for information security at
  ETH Zurich. http://bit.ly/2d5PV2I #PhD #CompSci  

+ 27-Sep-16: Postdoctoral position in information assurance,
  Luxembourg. http://bit.ly/2d5gkOm #PostDoc #CompSci 

+ 20-Sep-16: Doctoral scholarships in functional programming. University of
  Oxford. http://bit.ly/2d515SR #PhD #CompSci #FP 

+ 20-Sep-16: Open positions on secure compilation at Inria Paris funded by ERC
  grant. http://bit.ly/2cVsbPk #PhD #PostDoc #CompSci

+ 19-Sep-16: Postdoc Position at Virginia Tech on Isabelle/HOL, Blacksburg,
  Virginia, USA. http://bit.ly/2cjjyOS #PostDoc #CompSci #IsabelleHOL

+ 19-Sep-16: Postdoc position to work with us on the next generation of
  automated reasoning procedures. MPI, Saarbrücken, Germany
  http://bit.ly/2cjjRJL #PostDoc #CompSci

+ 16-Sep-16: Doctoral/Postdoctoral position in programming language theory &
  implementation. Univ. of Leuven http://bit.ly/2d1InQz #PhD #PostDoc #CompSci

+ 14-Sep-16: Functional Jobs: Software Engineer/Researcher at Galois Inc
  (Full-time) http://bit.ly/2cNCli0 #Job #CompSci #FP  

+ 14-Sep-16: Postdoctoral position in univalent foundations and type theory at
  the IAS. http://bit.ly/2cNy2Dl #PostDoc #CompSci

+ 14-Sep-16: #PhD and #PostDoc positions at IMDEA (Madrid) funded by an ERC
  grant "A Rigorous Approach to Consistency in Cloud
  Databases". http://bit.ly/2cNy6Tw #CompSci

+ 14-Sep-16: Simons-Berkeley Research Fellowships at the Simons Institute for
  the Theory of Computing, Berkeley CA (U.S.A.). http://bit.ly/2cNAfP5 #Job
  #CompSci 

+ 14-Sep-16: Postdoctoral position in proof theory, Vienna (Austria),
  http://bit.ly/2cNAgm9 #PostDoc #CompSci 

+ 14-Sep-16: Postdoctoral position (3 months) in proof complexity, Leeds
  (England). http://bit.ly/2cNByxq #PosDoc #CompSci 

+ 14-Sep-16: PhD student positions in mathematics (including logic), Helsinki
  (Finland). http://bit.ly/2cNBJc5 #PhD #Math #Logic

+ 09-Sep-16: #PostDoc position at TU Berlin in complexity theory, applied
  algebraic geometry, complexity and accuracy of numerical
  algorithms. http://bit.ly/2bWS0d7 

+ 09-Sep-16: Excelsior’s client is seeking a player/coach leader for their
  cryptocurrency development team. http://bit.ly/2bWQpnu #Job #Haskell 

+ 08-Sep-16: 2 PhD positions in formal methods at the Sirius Center in
  Oslo. http://bit.ly/2cEP2yM #PhD #CompSci 

+ 08-Sep-16: Lecturer position in Algorithms and Complexity, Leeds
  (England). http://bit.ly/2cr4zQA #Job #CompSci 

+ 08-Sep-16: PhD student position in information assurance,
  Luxembourg. http://bit.ly/2cEMIYu #PhD #CompSci 

+ 01-Sep-16: Associate Professor / Assistant Professor in Department of
  Computing. The Hong Kong Polytechnic University. http://bit.ly/2bZyrDT #Job
  #CompSci 

*** Agosto de 2016

+ 31-Ago-16: Postdoctoral position in security of cyber-physical
  systems. University of Verona. http://bit.ly/2bA0ltd #PostDoc #CompSci 

+ 31-Ago-16: Research Assistant / Officer in Theoretical Computer Science
  (Theory of Security). Swansea Univ., UK http://bit.ly/2bA1kcI #Job #CompSci 

+ 31-Ago-16: Research fellow positions at Birmingham and QMU London. 
  http://bit.ly/2bUFVrH #Job #CompSci

+ 31-Ago-16: Open PhD position in programming languages and statistical machine
  learning at KTH, Sweden http://bit.ly/2bzZbO7 #PhD #CompSci 

+ 27-Ago-16: Functional Jobs: Full-Stack Developer (Haskell/PureScript) at
  CollegeVine (Full-time) http://bit.ly/2bFqkgi #Job #Haskell

+ 27-Ago-16: Turn data into continuous insights with #Scala and #Haskell. Join
  their team in Seattle - http://hubs.ly/H0467_j0  

+ 25-Ago-16: Haskell positions at Facebook. http://bit.ly/2bkImAM #Job #Haskell

+ 24-Ago-16: Formal verification position at Intel. http://bit.ly/2buV4At #Job
  #CompSci 

+ 16-Ago-16: PhD student position in supervision of autonomous software
  systems, Utrecht (The Netherlands) http://bit.ly/2buX246 #PhD #CompSci 

+ 16-Ago-16: PhD student position in argument mining, Dundee
  (Scotland). http://bit.ly/2buXqzi #PhD #CompSci 

+ 16-Ago-15: Postdoc position in static and dynamic analysis of Android OS @
  CMU SV Campus. http://bit.ly/2balUx0 #PostDoc #CompSci #SeaHorn #JayHorn 

+ 16-Ago-16: Postdoc position in verification of Flight-Critical Software @ CMU
  SV Campus. http://bit.ly/2balUx0 #PostDoc #CompSci #SeaHorn #JayHorn  

+ 11-Ago-16: PhD position in computational music structure analysis using
  functional programming http://bit.ly/2b7QicA #PhD #CompSci 

+ 10-Ago-16: Functional Jobs: Head of data science at Capital Match (Full-time)
  http://bit.ly/2b5pF7U #Job #Haskell #DataScience

+ 09-Ago-16: 14 positions in Geo Data Science. http://bit.ly/2b2EA2Z #PhD
  #PostDoc #DataScience 

+ 08-Ago-16: PostDoc position at Wesleyan University on the topic of homotopy
  type theory. http://bit.ly/2aFCljU #PostDoc #CompSci 

+ 08-Ago-16: Four roles in Strats at Standard Chartered (London and
  Singapore). http://bit.ly/2aFpTjR #Job #Haskell 

+ 08-Ago-16: [#Job Ad] Haskell developer @ Atidot (Ramat-Gan,
  Israel). http://bit.ly/2b6r8wk  #Haskell via @RedditHaskell 

+ 05-Ago-16: Postdoctoral position, concurrency reasoning, Imperial College
  London. http://bit.ly/2aTqvoc #PostDoc #CompSci

+ 05-Ago-16: #Job: Assistant Professor – Critical computation and new
  media. Univ. of Toronto Mississauga http://bit.ly/2aTpm0b #CompSci

+ 05-Ago-16: PhD Studentship available in argument mining. 
  http://bit.ly/2aTpMn0 #PhD #CompSci

+ 05-Ago-16: PhD student position in knowledge representation and reasoning,
  Luxembourg. http://bit.ly/2aFPtEh #PhD #CompSci

+ 05-Ago-16: Ph.D. student position on "learning language through dialogue",
  Tilburg (The Netherlands). http://bit.ly/2aFP9pj #PhD #CompSci

+ 02-Ago-16: PhD studentship: Formal specification and verification of smart
  contracts. University College London. http://bit.ly/2aLtr7L #PhD #CompSci 

+ 02-Ago-16: PhD studentship: A certified compiler for smart
  contracts. University College London. http://bit.ly/2aLujct #PhD #CompSci 

+ 01-Ago-16: Postdoc in algorithms at The Open University of Israel
  http://bit.ly/2aETr3I #PostDoc #CompSci 

*** Julio de 2016

+ 31-Jul-16: Functional Jobs: Elm developer at Takt (Full-time)
  http://bit.ly/2aTnSAA #Job #Haskell 

+ 29-Jul-16: 2 PhD student positions in formal logic at the Univ. of Barcelona:
  verification of legal software in Coq. http://bit.ly/2aywcs9  

+ 29-Jul-16: #PhD student or #postdoctoral position on computational linguistics
  and dialogue processing, Amsterdam (The Netherlands). http://bit.ly/2ampr9A 

+ 28-Jul-16: #PostDoc at Ulm University. Topic is complexity theory, with a
  focus on Polynomial Identity Testing. http://bit.ly/2azXOLk #CompSci 

+ 27-Jul-16: Haskell developer job in India. http://bit.ly/2aJu5id #Job
  #Haskell 

+ 27-Jul-16: A Haskell developer for a full-time position at a Bay Area
  startup. http://bit.ly/2aJrLYs #Job #Haskell

+ 20-Jul-16: Two positions in computational linguistics (Postdoc or PhD
  student). Saarland Univ., Saarbruecken, Germany http://bit.ly/2awI8b0

+ 19-Ju-16: Faculty Position in Computer Sciences. Universidad Adolfo Ibanez,
  Faculty of Engineering and Sciences. #Job #CompSci 

+ 19-Jul-16: Professor of Computer Science/Technology. Zhejiang University,
  College of Natural Sciences http://bit.ly/2a6On9b #Job #CompSci 

+ 19-Jul-16: PhD fellowship in RNA Bioinformatics http://bit.ly/2a6Olyg

+ 19-Jul-16: PhD position in computational statistics for medical
  imaging. http://bit.ly/2a5bJt6 

+ 15-Jul-16: Lecturer in mathematics (info security) at School of Science, RMIT
  University, Melbourne, Australia http://bit.ly/29APbOR #Job #CompSci  

+ 13-Jul-16: Assistant or Associate Professorship in Theoretical Computer
  Science (tenure-track), Amsterdam. http://bit.ly/29MBMpO #Job #CompSci

+ 09-Jul-16: PhD or postdoc in semantics engineering in Language Designer's
  Workbench project at TU Delft. http://bit.ly/29nN6cL #PhD #PostDoc #CompSci

+ 07-Jul-16: PhD scholarship: Fully automated controller synthesis for UAV
  missions (Munich, Germany) http://bit.ly/29mIXSs #PhD #CompSci 

+ 07-Jul-16: PhD studentship in semantics and verification of heterogeneous
  programs at Queen Mary. http://bit.ly/29qgb75 #PhD #CompSci

+ 02-Jul-16: Full-time developer position opening at Université de Bordeaux for
  Fall 2016 or Fall 2017. http://bit.ly/29ANuS3 #Job #CompSci #Math

+ 02-Jul-16: Postdoc/PhD position at Innopolis University in area of program
  verification. http://bit.ly/29bZoTK #PhD #PostDoc #CompSci

*** Junio de 2016

+ 31-Jun-16: Postdoc position in verification at IMDEA, Madrid
  http://bit.ly/29bxLwm #PostDoc #CompSci

+ 30-Jun-16: Lectureships in Knowledge Representation and Reasoning (and other
  areas of computer science), Cardiff (Wales). http://bit.ly/29bm2h5 #Job
  #CompSci

+ 30-Jun-16: Several Funded PhD Studentships in Computer Science at IMT
  Lucca. http://bit.ly/29blNT9 #PhD #CompSci

+ 30-Jun-16: Lecturer (Teaching & Research) in Computer Science &
  Informatics. Cardiff University. http://bit.ly/296cX6z #Job #CompSci

+ 28-Jun-16: Postdoctoral associate position in London, working with
  Isabelle. http://bit.ly/293qfT6 #PostDoc #IsabelleHOL

+ 28-Jun-16: Postdoctoral researcher in combinatorial optimization at ETH
  Zurich. http://bit.ly/28ZO3n7 #PostDoc #CompSci

+ 27-Jun-16: Postdoc position on formal verification on security. Nanyang
  Technological University http://bit.ly/28VqDPf #PostDoc #CompSci

+ 27-Jun-16: Becas Iberoamérica, Santander Investigación. http://bit.ly/28VqpYp

+ 25-Jun-16: Haskell developer position at Scrive. Stockholm,
  Sweden. http://bit.ly/28SwS8h #Job #Haskell

+ 25-Jun-16: PhD position at VERIMAG, Grenoble, on combinations of Boolean
  reasoning and parametric linear programming. http://bit.ly/28S2rPF #PhD
  #CompSci

+ 25-Jun-16: #Job #Haskell developer @PicusSecurity in Ankara,
  Turkey. http://bit.ly/28RUI3X http://www.picussecurity.com

+ 24-Jun-16: #Job: Haskell Engineer - Machine Learning: Pioneering a new
  approach to the data security problem. Berkeley, California
  http://bit.ly/28UPQNn #Haskell

+ 22-Jun-16: Wrinkl, Inc. is seeking a Haskell Software Engineer for a
  full-time position located in NYC. http://bit.ly/28UTzth #Job #Haskell

+ 21-Jun-16: Jobs at Monash: Lecturer or Senior Lecturer (Data Science). Monash
  University. http://bit.ly/28RxTOJ #Job #DataScience

+ 17-Jun-16: Post doc at IT University of Copenhagen on a project on guarded
  recursion. http://bit.ly/24VfmVc #PostDoc #CompSci

+ 16-Jun-16: PhD position at INRIA Grenoble on formal methods for
  testing. http://bit.ly/1txvAZl #PhD #CompSci

+ 15-Jun-16: Postdoctoral position in epistemic protocol synthesis, Nancy
  (France). http://bit.ly/1PtXxFD #PostDoc #CompSci

+ 15-Jun-16: 2 #DataScience #PostDoc positions with Sune Lehmann in
  Copenhagen. https://t.co/M9FwVg7WpT

+ 14-Jun-16: Two Lectureships (Assistant Professorships) at St Andrews
  http://bit.ly/1YoP9yk #Job #Functional_programming #CompSci 

+ 14-Jun-16: On-site GHC-related Haskell/C opportunity at Positive Technologies
  (Moscow) http://bit.ly/1YoPDV8 #Job #Haskell

+ 13-Jun-16: Postdoctoral positions at Stanford University on the development
  and application of automated reasoning techniques. http://bit.ly/28xLYc3
  #PostDoc #CompSci

+ 13-Jun-16: 2 postdoc positions: Researcher in algorithmics and semantics of
  higher-order computation. Univ. of Oxford http://bit.ly/1tmGwID #PostDoc
  #CompSci

+ 13-Jun-16: Job offer: close-to-industry research position.
  http://bit.ly/1rl9lDO #PostDoc #Type_theory #Formal_methods #Verification

+ 09-Jun-16: One #PhD or #PostDoc position to develop further the theoretical
  foundations of monitorability. Reykjavik Univ. http://bit.ly/1YfCptS #CompSci

+ 09-Jun-16: #Job: Senior Big Data Developer. London, United
  Kingdom. http://bit.ly/1RXPaBU #Scala #BigData

+ 09-Jun-16: Fancy working on big data challenges with #Scala & #Spark to bring
  green energy to more people? - http://hubs.ly/H03c-p00

+ 09-Jun-16: Work with Scala in Dublin to help build a distributed HR
  management platform - http://hubs.ly/H03c-p20 #Job #Scala

+ 09-Jun-16: CircleCI is seeking a Product Engineer for a full-time position
  located in San Francisco or Toronto. http://bit.ly/1YfAzt3 #Job #Clojure

+ 09-Jun-16: Professor Software technology at Utrecht University
  http://bit.ly/1RXNckV #Job #CompSci

+ 08-Jun-16: PhD student position on formal methods for testing of networks of
  controllers, Grenoble (France) http://bit.ly/1X9JHjd #PhD #CompSci

+ 08-Jun-16: Postdoc in formal methods for system-level security at Univ. Lille
  & CNRS, France. http://bit.ly/1X9JCfj #PostDoc #CompSci

+ 07-Jun-16: Jobs in verified refactoring for OCaml and CakeML at the
  University of Kent. http://bit.ly/1RWhtAv #PostDoc #CompSci

+ 07-Jun-16: Postdoc position in type systems at the New Jersey Institute of
  Technology (NYC area) http://bit.ly/1teDmY4 #PostDoc #CompSci

+ 06-Jun-16: Senior Clojure position where you can build a new approach to personal
  finance. http://hubs.ly/H03cmF70 #Clojure

+ 05-Jun-16: Postdoctoral position in machine learning at the University of
  Pennsylvania. http://bit.ly/28czZQZ #PostDoc #CompSci 

+ 05-Jun-16: PhD Position in Machine Learning. AIT Austrian Institute of
  Technology, Department of Technology http://bit.ly/1Uq1T1K #PhD #CompSci

+ 05-Jun-16: PhD Student in Computer Science. University of Innsbruck,
  Department of Computer Science. http://bit.ly/1Uq1FYs #PhD #CompSci

+ 04-Jun-16: Lispjobs: Secure Outcomes, contract Common Lisp programmer
  http://bit.ly/1XqNycC #Job #Common_Lisp 

+ 01-Jun-16: PhD student position in Logic for Multiscale Network Modelling,
  Leeds (England). http://bit.ly/1WZZhOm #PhD #CompSci

+ 01-Jun-16: Associate senior lectureship (4y) in computational linguistics,
  Gothenburg (Sweden). http://bit.ly/1WZZtNq #Job #CompSci

+ 01-Jun-16: Postdoctoral fellowship in security of cyber-physical
  systems. http://bit.ly/1WZZqRZ #PostDoc #CompSci

+ 01-Jun-16: Functional Jobs: Software Engineer (Haskell/Clojure) at Capital
  Match(Full-time) http://bit.ly/1Pm3b1C #Job #Haskell

+ 01-Jun-16: Functional Jobs: CTO (Haskell/Clojure) at Capital Match
  (Full-time) http://bit.ly/1Pm2qWr #Job #Haskell

*** Mayo de 2016

+ 31-May-16: PhD student or postdoctoral position on oligomorphic clones,
  Vienna (Austria). http://bit.ly/22w5VvN #PhD #PostDoc #Logic

+ 30-May-16: Two-year postdoctoral positions at the Institute UC3M-BS of
  Financial Big Data, Univ. Carlos III de Madrid, Spain. http://bit.ly/27YHdrP
  #PostDoc

+ 30-May-16: Semantic systems application architect (KTP associate). Univ. of
  Manchester. http://bit.ly/1U6ZaKD #Job #CompSci

+ 28-May-16: PhD student position in knowledge-based systems, Lisbon
  (Portugal). http://bit.ly/1Wsn8WW #PhD #CompSci 

+ 26-May-16: PhD position at INRIA Grenoble: "Formal proofs for the analysis of
  real-time systems in Coq" http://bit.ly/1qL7uYF #PhD #CompSci #Coq

+ 26-May-16: PhD position at INRIA Grenoble: "Analysis and types for safe
  dynamic software configurations". http://bit.ly/1TLjUvp #PhD #CompSci

+ 26-May-16: PhD position at INRIA Grenoble: "Programming IoT and software
  defined radio with dynamic data-flow models of computation"
  http://bit.ly/1TLkCZF #PhD #CompSci

+ 21-May-16: Funded PhD (3 years) in program analysis at IRIF (Paris,
  France). http://bit.ly/1sIYEg0 #PhD #CompSci

+ 21-May-16: Funded Post-doc positions in program analysis and verification at IRIF
  (Paris, France). http://bit.ly/1sIYzZY #PostDoc #CompSci

+ 21-May-16: Postdoctoral position in stochastic games, Bordeaux
  (France). http://bit.ly/1VemACJ #PostDoc #CompSci

+ 19-May-16: Hiring Haskell engineers at LeapYear, a data security
  company. http://bit.ly/22w6ohy #Job #Haskell 

+ 18-May-16: Target Haskell data scientist job in Sunnyvale, California, United
  States. http://bit.ly/1WEjh98 #Job #Haskell #DataScience

+ 15-May-16: Research associate positions in refactoring functional programs
  and formal verification (for CakeML). Univ. of Kent http://bit.ly/1spwTci
  #Job #CompSci

+ 12-May-16: #PhD (#PostDoc) position in software verification and synthesis at the Max
  Planck Institute for Software Systems http://bit.ly/1WsRBVb #CompSci

+ 12-May-16: Postdoctoral position in logic, Amsterdam (The Netherlands). 
  http://bit.ly/1QZCauY #PostDoc #Logic #CompSci

+ 12-May-16: PhD student position in Algorithms, Bergen (Norway). http://bit.ly/1QZCbz8 
  #PhD #CompSci

+ 10-May-16: PostDocs and PhD positions on the project "Skye: A programming
  language bridging theory and practice for scientific data
  curation". http://bit.ly/27a1c6y

+ 06-May-16: Several postdoctoral and Ph.D. positions at ENS Lyon, France, in the area of
  verification and certification. http://bit.ly/1ZmUUKQ #PhD #PostDoc #CompSci

+ 06-May-16: Two #PhD studentships in the area of correct and efficient programming for
  concurrent and parallel systems. IC, London. http://bit.ly/1ZmQ2FJ #CompSci

+ 06-May-16: Postdoctoral position in Algorithms, TU Munich (Germany). 
  http://bit.ly/1ZmRV5c #PostDoc #CompSci

+ 02-May-16: Verification of randomized algorithms: open PhD/post doc
  position. TUM, Munich http://bit.ly/1VGEYVS #PhD #CompSci #IsabelleHOL

*** Abril de 2016

+ 30-Abr-16: PhD position in formal modelling and verification for high
  assurance at KTH Royal Institute of Technology. http://bit.ly/1SE6FsD 
  #PhD #CompSci

+ 29-Abr-16: Postdoctoral position in mathematical logic, Salerno
  (Italy). http://bit.ly/248n96Y #PostDoc #Logic

+ 29-Abr-16: Postdoctoral or PhD student position in computation with bounded resources,
  Innsbruck (Austria). http://bit.ly/248njv1 #PhD #PostDoc #CompSci

+ 28-Abr-16: Postdoc position in domain-specific languages. Tufts
  University. http://bit.ly/1N2h1p5 #PostDoc #CompSci

+ 26-Abr-16: PhD student position in formal modeling and analysis of security,
  Rennes (France). http://bit.ly/1pArNaF #PhD #CompSci

+ 26-Abr-16: PhD student position in theoretical computer science, Karlsruhe
  (Germany). http://bit.ly/1pArVHo #PhD #CompSci

+ 23-Abr-16: Ph.D. position in security modeling at IRISA in Rennes, France. 
  http://bit.ly/1VJohtd #PhD #CompSci

+ 18-Abr-16: Contract postdoctoral position in biological programming languages at
  Microsoft Research Cambridge. http://bit.ly/1VdQfg4 #PostDoc #CompSci

+ 18-Abr-16: Verification of randomized algorithms in the theorem prover Isabelle: open
  PhD/post doc position at TUM. http://bit.ly/1VdRgVl #PhD #CompSci 

+ 18-Abr-16: Postdoc position in semantics and effects. University of
  Birmingham. http://bit.ly/1VdSgcc #PostDoc #CompSci

+ 14-Abr-16: PostDoc in algorithms and complexity at University of Oxford. 
  http://bit.ly/1ShlDJZ #PostDoc #CompSci

+ 12-Abr-16: Funded PhD on concurrency modelling using ideas from formal
  verification at Univ. of York, UK. http://bit.ly/25Wi1RU #PhD #CompSci

+ 10-Abr-16: PhD student position in on-line privacy using multi-agent systems,
  London (England). http://bit.ly/1S3ulbu #PhD #CompSci

+ 01-Abr-16: Postdoc ad: quantum-computing programming
  languages. http://bit.ly/1SFCzqi #PostDoc #CompSci 

*** Marzo de 2016

+ 31-Mar-16: PhD position in guarded homotopy type theory. 
  http://bit.ly/1TlfvPZ #PhD #CompSci

+ 27-Mar-16: PhD position at LaBRI Bordeaux France. Subject: higher-order
  verification. http://bit.ly/1VOCvaA #PhD #CompSci

+ 20-Mar-16: PhD and Post-Doc positions in formal methods at Chalmers. 
  http://bit.ly/1SaKJ9S #PhD #PosDoc #CompSci 

+ 17-Mar-16: 2 Ph.D positions on Formal Methods for Rule-based agent safety and
  concurrent system analysis (U. of Oslo). http://bit.ly/1LtAnTj #PhD #CompSci

+ 06-Mar-16: PhD studentship on "Declarative Programming for Data Science"
  http://bit.ly/1U3rbX1 #PhD #CompSci #DP #DataScience

*** Febrero de 2016

+ 26-Feb-16: Two postdoc positions in reasoning about concurrent and distributed
  systems. Imperial College London. http://bit.ly/1QlEDAN

+ 23-Feb-16: 4-year PhD studentship on "Declarative Programming for Data
  Science", University of Edinburgh. http://bit.ly/1OrL7Mh #CompSci #PhD

+ 23-Feb-16: PhD and Post-Doc positions in formal methods and security,
  Chalmers University of Technology. http://bit.ly/1RkdZL0 #PhD #CompSci

+ 18-Feb-16: Postdoctoral Research Fellow in Artificial Intelligence. Western
  Sydney University. http://bit.ly/1U9VjAh #PostDoc #CompSci

+ 15-Feb-16: Postdoc position at Tulane on the "Semantics, formal reasoning,
  and tool support for quantum programming" project. http://bit.ly/1KQyEXF #CompSci

+ 11-Feb-16: Phd/PostDoc positions in formal methods for distributed systems at
  University Paris Diderot, France. http://bit.ly/1WglkfP #PostDoc #CompSci

+ 03-Feb-16: Postdoctoral position in functional, constraint and/or logic programming at
  KU Leuven. http://bit.ly/1PSet7A #PostDoc #CompSci

*** Enero de 2016

+ 20-Ene-16: Postdoc position on hardware verification at NTU
  Singapore. http://bit.ly/1ltVFDH #PostDoc #CompSci 

+ 20-Ene-16: Postdoc position on security protocol verification at NTU
  Singapore. http://bit.ly/1ltVUP1 #PostDoc #CompSci 

+ 15-Ene-16: Postdoctoral and PhD positions in LFCS on graph databases,
  provenance, and programming languages. http://bit.ly/1Zztq9z #PostDoc #CompSci

+ 12-Ene-16: Postdoc position at Penn on the DeepSpec
  project. http://bit.ly/1ZhC4Ux #PostDoc #CompSci

+ 09-Ene-16: ERC project "RustBelt" on foundations for Rust -- Postdoc and PhD
  positions available! http://bit.ly/1Pk6osr #PostDoc #PhD #CompSci

+ 07-Ene-16: Postdocs at Tulane on semantics of quantum programming
  languages. http://bit.ly/1SCm8fI #PostDoc #CompSci 

 



